### ISSUE TITLE
transition to 2.80

### ISSUE THREAD

**Issue by slepyhed** [animate1978/MB-Lab#10]
Folks,

I spent some time today looking into what its going to take to move over to 2.80+

The changes to the UI mean there need to be certain changes to MB-Lab, and I'm not sure if it will be compatible with 2.7x afterwards.

This page shows helpful info on how to change things:
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/UI_API

I'm going to add a few tasks to the 2.80 port project based on things I found out. There is sure to be more that needs to be done, I'm still fooling around with it.

In the meantime, I wanted to ask for a discussion about how to transition to 2.80? Do we fork now and try to unify after 2.8 beta ends? Do we go to 2.8 now? Maybe we just investigate 2.8 conversion now and implement the changes later? Other ideas?

**Comment by animate1978** [comment]
> 
> In the meantime, I wanted to ask for a discussion about how to transition to 2.80? Do we fork now and try to unify after 2.8 beta ends? Do we go to 2.8 now? Maybe we just investigate 2.8 conversion now and implement the changes later? Other ideas?

I would say wait a little while until the beta ends, or at least until the API is stable enough so we don't have to re work anything too much later. I was personally going to wait until after MB-Lab goes to 1.7.0 before we begin the road down to Blender 2.80 because once we go down that road it is no turning back.

**Comment by animate1978** [comment]
Well a surprise code was dropped last night, I tested the code to make sure it functioned (it did) so I merged the code into master.
