### ISSUE TITLE
Messed up model

### ISSUE THREAD

**Issue by AtifPerwez** [animate1978/MB-Lab#104]
**Describe the bug**
After finalizing the character when I am disabling any modifier in viewport it messed up all model and then doing anything remove everything from the scene and then I have to close a blender.

**To Reproduce**
1. Finalize the character
2. Do some movement in pose mode and then go to the Modifiers tab on a model.
3. Disable any modifier.

**Expected behavior**
It should remain the same but it is messing up the whole blender

**Screenshots**
![error](https://user-images.githubusercontent.com/48828041/54820397-0e147200-4cc5-11e9-9572-fc5c36473b37.png)
This is happening all the time I tried many things but it keeps happening.

**Logs**
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok

**Comment by animate1978** [comment]
This is in relation to a bug in Blender, it's a known issue you can read here - https://github.com/animate1978/MB-Lab/issues/20

**Comment by AtifPerwez** [comment]
So how can we use it in blender any suggestions or we can't.

**Comment by animate1978** [comment]
The problem lies in the bendy bones, which in MB-Lab are the "Muscles", a feature that works in Blender 2.79 but is a bug that is still unresolved in the Beta. Sadly.

Our work around is simply to not use the muscle feature at this time. Hopefully this bug will be resolved.
