### ISSUE TITLE
[v1.7.3]Can't install on MacOS 10.4.4 - Blender 2.80 2019-03-31

### ISSUE THREAD

**Issue by foxnoodles** [animate1978/MB-Lab#105]
Ok so renamed the zip file to MBLab173.zip (removed dashes and periods) 

Went to blender > edit > preferences > addons > [selected the file] > installed from file. No errors. 
The character category does not appear in the addons list. 
Same thing with older builds of Blender, and same thing with v1.7.2,
what am I doing wrong?

**Comment by animate1978** [comment]
I referred your question to someone that has a Mac, as I do not. Hopefully this gets resolved soon.

**Comment by StefanUlbrich** [comment]
Will try myself on Monday. Which blender build do you have? In the meanwhile, could you please open blender from a terminal (or iTerm):
```/Applications/Blender./blender.app/Contents/MacOS/blender```
(or similar, look in Finder where the app is stored). There should be hints on the command line that help narrowing the problem.

**Comment by foxnoodles** [comment]
Pretty much any build since January (including today's build). Dunno about older ones, never tried those.

The terminal only gives this after install:

`Modules Installed () from '/Users/fox/Downloads/MBLab173.zip' into '/Users/fox/Library/Application Support/Blender/2.80/scripts/addons'`

Yet no "character" appears in Category list dropdown

**Comment by StefanUlbrich** [comment]
Can you check the install with  `ls /Users/"myuser"/Library/Application Support/Blender/2.80/scripts/addons`?

**Comment by foxnoodles** [comment]
`ls /Users/"myuser"/Library/Application\ Support/Blender/2.80/scripts/addons 
MB-Lab-1.7.3	__init__.py`
and 
` ls /Users/fox/Library/Application\ Support/Blender/2.80/scripts/addons/MB-Lab-1.7.3 
data
docs
__init__.py
animationengine.py
addon_updater_ops.py
addon_updater.py
humanoid.py
algorithms.py
gpl-3.0.txt
agpl-3.0.txt
proxyengine.py
.pylintrc
morphengine.py
materialengine.py
skeletonengine.py
facerig.py
license.txt
CHANGELOG.md
preferences.py
utils.py
README.md`

**Comment by foxnoodles** [comment]
Okay I renamed the MB-Lab-1.7.3  to MB-Lab in "scripts/addons/" and that fixed it. But I think that's a bug

**Comment by StefanUlbrich** [comment]
you were too fast :-) I was just trying to rename the folder. 
Agreed, this needs to be looked into.

**Comment by foxnoodles** [comment]
Haha, glad we figured it out, I would never checked the terminal if not you lol

**Comment by StefanUlbrich** [comment]
Welcome! Can you do me a favor and install the file without changing the name of the zip?

> Ok so renamed the zip file to MBLab173.zip (removed dashes and periods)

I don't know how blender decides where to install the addon (I installed it manually for development)

**Comment by foxnoodles** [comment]
That was the first thing I tried actually. Doesn't change anything

**Comment by fcpineiro** [comment]
I got this same error right now on the actual build for 1.7.3.

- I'm using Windows 10 64-bit.
- Clean install (both blender + mb-lab).
- Didn't got Characters category showing up.
- Renamed the installed addon folder to just "MB-Lab"
- Everything works fine.

**Comment by potocpav** [comment]
Just the same as @fcpineiro, this time on:

* Ubuntu 18.04,
* Blender 2.80, 2019-04-15 (5ac76), clean install

**Comment by vlad1777d** [comment]
Same for Blender 2019-04-21 (clean install), Linux Mint 19.1 .

**Comment by miked63017** [comment]
I tried this rename in the addons directory and it worked, kind of. I am new to add ons in blender but pretty good with python in general, thinking maybe it could be python3x related?

![Screen Shot 2019-04-26 at 4 12 20 PM](https://user-images.githubusercontent.com/5140447/56836927-449e5900-683e-11e9-9a19-3c0bb9f666c6.png)

**Comment by ldo** [comment]
As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.

I’m sure I speak for the maintainer of this repo, and for all other repo maintainers.

**Comment by animate1978** [comment]
What version of MB-Lab are you trying to install? If you are using Blender 2.79 you need this version -
[MB-Lab 1.6.5](https://drive.google.com/open?id=1Wxly5xEYQwPvCvo1Gn95r7iPk02PTWD-l)

**Comment by miked63017** [comment]
@ldo generally speaking I agree with you, but this error was not in a terminal, and blender(at least in osx) would not let me highlight and copy this text. Also, you probably do speak for most maintainers, I myself hate it when I get screenshots rather than text, but I would also prefer the screenshot over a vague description of an error because the user could not copy the text. I hope you will understand the reasoning, maybe this would be a good feature request for the blender project.

@animate1978 I am using blender 2.79b and MB-Lab 1.7.4b. I will try using an older version at some point this weekend and report back. Thanks!

**Comment by miked63017** [comment]
@animate1978 that version seems to work, at least no errors yet after an install. Thanks again!

**Comment by dluxcru** [comment]
Have an issue that looks similar to this one. https://blender.stackexchange.com/questions/141470/mblab-1-7-4-add-on-refuses-to-install-in-blender-2-8-beta/141487

**Comment by animate1978** [comment]
Closing this one since it has been solved
