### ISSUE TITLE
Numpy multiarray error when attempting to activate plugin

### ISSUE THREAD

**Issue by drewpotter** [animate1978/MB-Lab#106]
**Describe the bug**
I am getting an error when I try to activate the plugin with the latest Blender master branch code built from source.

**To Reproduce**
1. Go to 'Edit' > 'Preferences' > 'Add-ons'
2. Click on 'Enable an add-on'

**Expected behavior**
I expected the plugin to activate.

**Screenshots**

**Additional context**
Built from source on Ubuntu 18.04

**Logs**
`To format it correctly, logs should go in between these:`
```
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' [I removed the full path here]/blender/build/bin/2.80/python/lib/python3.7/dist-packages/numpy/core/__init__.py)
```

**Comment by StefanUlbrich** [comment]
Hey .. just installed and used the plugin with a fresh download from blender.org (also 18.04).
I did not encounter this issue. 

can you try the following lines ?

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
[I removed the full path here]/blender/build/bin/2.80/python/lib/python3.7m  get-pip.py 
[I removed the full path here]/blender/build/bin/2.80/python/lib/python3.7m  -m pip -U numpy
```

Is there any specific reason on why you don't use the distributed package but build from sources?

**Comment by drewpotter** [comment]
My apologies @StefanUlbrich I tried it out with the official build and it loads of fine with no problem. It must be my build from source which is the issue here as you kindly pointed out. The reason why I am using the latest source build is that I am doing some development work with Blender, partly I wish to make my own plugin for Blender but also I am interested in making Blender work under the QtWayland compositor.
