### ISSUE TITLE
SYNTAX ERROR

### ISSUE THREAD

**Issue by dongooden** [animate1978/MB-Lab#107]
I'm receiving this syntax error on PC for blender 2.79. The box is there for me to check, but when i do it gives me syntax error: invalid syntax

**Comment by MugenAnimations893** [comment]
I am deaing with the same issue. i hope this gets resolved soon

**Comment by animate1978** [comment]
I am not sure where this bug would be without more information.

The current release is for Blender 2.80 if you are trying to install this for 2.79 this might be your problem. The last version for 2.79 was MB-Lab 1.6.5 which you can get here : https://github.com/animate1978/MB-Lab/releases/tag/1.6.5b

**Comment by dongooden** [comment]
thats probably the problem thanks
