### ISSUE TITLE
Quick startup for noobs

### ISSUE THREAD

**Issue by FabriceSalvaire** [animate1978/MB-Lab#108]
I read the manual but the screenshots doesn't correspond to the 2.80

I cannot figure out how to find the MBLab menu / panel to start to do something.

**Comment by blaisefaint** [comment]
The MBLab menu / panel is now to the right. Have you been able to find the User Preferences to install the Lab?
![Annotation 2019-04-12 090130](https://user-images.githubusercontent.com/40342854/56039365-2a269480-5d02-11e9-85f3-a485d3661f0d.jpg)

**Comment by FabriceSalvaire** [comment]
Thanks ! I got it.
