### ISSUE TITLE
Shader problems

### ISSUE THREAD

**Issue by SleeperG** [animate1978/MB-Lab#115]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Logs**
`To format it correctly, logs should go in between these:`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.
Hello. I'm trying to make different ethnic groups but the complexion & skin value slider's are doing absolutly nothing. These are character's that I imported from you're original installment which were working perfectly then. I'm attaching one of my files so that you can see what I mean. Thx.
Well that didn't work Blend files aren't supported.

**Comment by SleeperG** [comment]
Hello. I'm trying to make different ethnic groups but the complexion & skin value slider's are doing absolutly nothing. These are character's that I imported from you're original installment which were working perfectly then. I'm attaching one of my files so that you can see what I mean. Thx.
Well that didn't work Blend files aren't supported.

**Comment by animate1978** [comment]
I just did a quick fix to the skin complexion, it was related to the SSS map, so this should fix the issue if you update

**Comment by SleeperG** [comment]
I just updated it but my african american skin still looks caucasian.

**Comment by SleeperG** [comment]
Thx for all your work.

**Comment by animate1978** [comment]
Did the update go on your end?
