### ISSUE TITLE
Size matters

### ISSUE THREAD

**Issue by SleeperG** [animate1978/MB-Lab#116]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is or a new idea.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I'd like to request having character's initalize at real scale. Physic issues would be eliminated then. It's difficult rescaling the character & then trying to reajust the lighting setup for those of us that aren't good lighter's.  or even extend the range of the body slider in body measurments to go up to 7ft. at least. Thx

**Comment by animate1978** [comment]
With the current code it is possible to achieve the height requirements you describe.

We are looking into changing some aspects of this though.

Closing this as it is already being planned to change aspects of the modeling process.
