### ISSUE TITLE
new function take a look

### ISSUE THREAD

**Issue by DemonRem** [animate1978/MB-Lab#118]
please can you add a function like that , a pop up additional to the tool pop up , that on the end of editing the model there will be a pop up function too like copy the model base parts to create a new parts for the base model? if you know what i mean , its can be very nice function

**Comment by NumesSanguis** [comment]
It's great to see you interested in this project! Some advice on how people are more likely to help you with your feature request:

- Make the title about your feature request. I'm pretty sure the new function could be helpful for some people, but "new function" doesn't tell us anything about what function you want. Therefore, something like: "Feature request: Copy model base parts as for new base model". That will make it easier to find your issue.
- A 3-line explanation is hard to understand, especially for people who are not a native level English. Consider breaking it down in short, simple sentences.
- When you click on the green button `New issue`, you see "Feature request" with a green button saying `Get started`. Now you can file an issue where some basic questions are asked to make your feature request easier to understand for other people. Please answer those:

```
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is or a new idea.

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```

**Comment by animate1978** [comment]
Not sure what you mean here, this is being closed for now until further information is supplied
