### ISSUE TITLE
Python dev

### ISSUE THREAD

**Issue by gr4viton** [animate1978/MB-Lab#119]
Hi there, where do i start? I work in python and played with blender.
Do you have any roadmap, or issues which should be handled first?

I do want to start contributing, or at least try. I have a few projects, but never really participated in open project. :O huh, scary.

**Comment by gr4viton** [comment]
well it is 4 in the morning - roadmap is probly this right?
https://github.com/animate1978/MB-Lab/projects/1

**Comment by animate1978** [comment]
Welcome! The roadmap is a great place to start :)

Also don't feel bad about your skill level, all are accepted. This is my first BIG project so we all are on the same boat and I am not a skilled programmer.

**Comment by Scroungy** [comment]
Was going to open a post of my own, but seeing as someone else has the idea, I'll just tack on to this one. Although I've been programming with Java for a while, and c++, I don't mind getting back to Python! I'd love to contribute, and as gr4viton said, I don't entirely know where to start, so it'd be sweet to have some guidelines!

**Comment by animate1978** [comment]
Hello @Scroungy , welcome to the project!

Currently I am trying to figure out some bugs that have popped up recently, ones that I have been unable to solve.

https://github.com/animate1978/MB-Lab/issues/120
https://github.com/animate1978/MB-Lab/issues/101

As for guidelines, if you do some modifications, make sure that when you commit, you do so to the Dev branch.

If you want to do some live chatting you can also join my Discord server : https://discord.gg/FuJGcVN

**Comment by animate1978** [comment]
I think the next issues we should focus on is the Auto-Updater issues here -

https://github.com/animate1978/MB-Lab/issues/101
https://github.com/animate1978/MB-Lab/issues/105
https://github.com/animate1978/MB-Lab/issues/127

These involve the Auto-Updating code and I have no idea why it is not functioning correctly, these have been around for some time too
