### ISSUE TITLE
"toes_R" is not connected in the rig

### ISSUE THREAD

**Issue by danielenger** [animate1978/MB-Lab#121]
"toes_R" is not connected in the rig.
use_conncet should be True

**Comment by animate1978** [comment]
OK so I located in humanoid_library.blend the offending bone.

However when trying to check the "Connected" box, it will not and throws up a warning dialogue.

![toes_r_connect_bug_01](https://user-images.githubusercontent.com/479115/58251050-5af9e080-7d28-11e9-81c5-85c81aa74824.png)

**Comment by danielenger** [comment]
You can only edit bone properties in edit mode.

**Comment by animate1978** [comment]
AH YES! Will look at it again

**Comment by animate1978** [comment]
Ok it is fixed now
