### ISSUE TITLE
MB-Lab 1.7.4 Auto-Updater register bug

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#127]
![register_bug_01](https://user-images.githubusercontent.com/479115/58418697-1fc02000-804e-11e9-9f39-d63d60927d08.png)
Have an issue that looks similar to this one. https://blender.stackexchange.com/questions/141470/mblab-1-7-4-add-on-refuses-to-install-in-blender-2-8-beta/141487

_Originally posted by @dluxcru in https://github.com/animate1978/MB-Lab/issues/105#issuecomment-496061243_

This is just to reference... not my bug

**Comment by dluxcru** [comment]
So this is a separate bug from #105 then?

**Comment by animate1978** [comment]
It might be related I think. It has to do with registering classes, which the Auto-Updater code has been having issues....
