### ISSUE TITLE
Brainstorming about MB-Lab - Google forms

### ISSUE THREAD

**Issue by NumesSanguis** [animate1978/MB-Lab#129]
Do we want to put the following (temporarily) in the wiki?

-----

Cross-post from:
- blenderartist: https://blenderartists.org/t/mb-lab-release-for-blender-2-80/1138777/235
- Discord channel: https://discordapp.com/invite/FuJGcVN

-----
Hello users of MB-Lab!

This add-on has come far since we as a community took over the development. We have 230 posts here and already 100+ users on the Discord channel!
Many users have asked on how they can contribute, so I thought it would be nice if we can aggregate everyone's view and usage of this add-on. With those insights, we can understand this community better and increase motivation ^-^

Therefore, I made a **Google forms with brainstorm-like questions**, please fill it out!:
[Google forms link :) (click me)](https://forms.gle/CZmnHAJ8JxXFQgrA6)

**Results** will be shared on blenderartist, the Discord channel and here from **2019-06-02** (you can still fill it out later as well). The reason to not share it directly, is that seeing other people's answers might influence your answers. That can reduce the variety of the answers given, the opposite of what we want to achieve here.

**Comment by animate1978** [comment]
Added to the wiki

**Comment by NumesSanguis** [comment]
Thank you, found it!
https://github.com/animate1978/MB-Lab/wiki/Brainstorm

**Comment by NumesSanguis** [comment]
Today is the last day if you want your opinion / inspiration about the future of MB-Lab be included in the analysis!
Google forms link: https://forms.gle/CZmnHAJ8JxXFQgrA6
