### ISSUE TITLE
skin shader too reflective in EEVEE vs Cycles

### ISSUE THREAD

**Issue by killarny** [animate1978/MB-Lab#130]
The EEVEE version of the skin shader is way too reflective, almost as if the character has been dipped in oil, compared to the same lighting conditions rendered in Cycles.

Here is a comparison, using an HDRI to rule out lighting setup differences between the engines:

![mblab-skin-render-comparison](https://user-images.githubusercontent.com/29001/58606598-2b882e00-826a-11e9-9672-ebc946561e06.png)

Edit: this is using the addon as cloned from master at commit 466ea54, and a newly created character with the default settings for the F_CA01 preset.

**Comment by animate1978** [comment]
I agree, in retrospect, that the EEVEE shader network is too reflective, I will have to make some changes to this.

**Comment by animate1978** [comment]
This has been modified in the Dev branch, will be merged later
