### ISSUE TITLE
IK and Muscle bug

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#131]
**Describe the bug**

Not sure exactly what this affects, this was reported thru the console.

**To Reproduce**

Create a new character with IK and Muscles checked.

**Expected behavior**

The character created without "bugs" in the console.

**Screenshots**

**Additional context**

Again this is only after initial testing, this does not seem to affect anything else in MB-Lab.

**Logs**
`
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, c
omponent name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, compon
ent name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
`

**Comment by animate1978** [comment]
Upon further research this is related to https://github.com/animate1978/MB-Lab/issues/137#issue-456673318

**Comment by dribeiro73rj** [comment]
Additional context

this bug leads to render interruption

find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF68CE6757A
Module  : %blender_path%\blender-2.81.0-git.f88022b96f3a-windows64\blender.exe

**Comment by animate1978** [comment]
Just tested IK and Muscle character creation with no issues as described here.
