### ISSUE TITLE
Saved clothing does not load

### ISSUE THREAD

**Issue by kity0114** [animate1978/MB-Lab#132]
**Describe the bug**
When you save the newly created clothing file, it appears in the library folders assets drop down but does not load 

**To Reproduce**
1. Modify or create an article of clothing
2. Save clothing as blend file (or export it as FBX OR OBJ file, then import and save as .blend file) in the assets folder 
3. open MB-lab tab (-N to make it show)
4. look for new clothing in the assets folder and select it on the assets library drop down
5. click it

**Expected behavior**
Nothing loads

**Logs**
`To format it correctly, logs should go in between these:`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.

**Comment by animate1978** [comment]
I believe this issue has been solved in the chats?

**Comment by kity0114** [comment]
Correct


-Kathia
