### ISSUE TITLE
Question regarding BVH bone correction using Utility tool

### ISSUE THREAD

**Issue by vini-guerrero** [animate1978/MB-Lab#133]
Hi, first of all I'd like to congratulate you guys on this project, it's pretty straight forward and I shall be letting other people know about this as I found it very amazing! 
Second, I might be doing it wrong, don't know, but I tried to correct my bvh animation (pulled from Mixamo) into a fresh simple character created using MB-Lab and I ran into this error:

<img width="1440" alt="Screen Shot 2019-06-07 at 00 59 55" src="https://user-images.githubusercontent.com/18181786/59080632-28232100-88c0-11e9-866a-ddbb93665b82.png">

Should I be fixing the feet bone & head bones in pose mode?
Thanks in advance, best regards!

**Comment by animate1978** [comment]
I think this too has been solved via chats
