### ISSUE TITLE
Face Rig Bug - 1.7.5 dev branch

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#139]
**Describe the bug**
Testing the addon for any and all situations, this one is a new one. Once you create a finalized character, click on Create Face Rig. 

EDIT - This is using the latest Dev branch.

**To Reproduce**
1. Create a character
2. Finalize
3. Click Create Face Rig
4. See log and screenshot

**Expected behavior**

Create a face rig without a security warning.

**Screenshots**

![Screenshot from 2019-06-30 09-23-59](https://user-images.githubusercontent.com/479115/60398057-92bf2980-9b19-11e9-930c-de7b70a97e63.png)

**Additional context**

**Logs**
Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 1822, in execute
    if not facerig.setup_face_rig():
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 155, in setup_face_rig
    add_rm_drivers(drivers)
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 114, in add_rm_drivers
    populate_variable(v, var)
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 62, in populate_variable
    face_rig = bpy.data.objects[var['targets'][0]['id_name']]
KeyError: 'bpy_prop_collection[key]: key "MBLab_skeleton_face_rig" not found'

location: <unknown location>:-1

location: <unknown location>:-1
ERROR (bke.fcurve): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/blenkernel/intern/fcurve.c:1381 driver_get_variable_property: driver has an invalid target to use (path = (null))
	BPY_driver_eval() - restricted access disallows name 'ph_AI', enable auto-execution to support

Error in Driver: The following Python expression failed:
	'var + (ph_AI/3) + (ph_E/15) + (ph_U/15) + (ph_CDG/7.855) + (ph_L/6.33468)'

**Comment by animate1978** [comment]
Even with auto-exec saved in the config file...

***
Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 1822, in execute
    if not facerig.setup_face_rig():
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 155, in setup_face_rig
    add_rm_drivers(drivers)
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 114, in add_rm_drivers
    populate_variable(v, var)
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 62, in populate_variable
    face_rig = bpy.data.objects[var['targets'][0]['id_name']]
KeyError: 'bpy_prop_collection[key]: key "MBLab_skeleton_face_rig" not found'

location: <unknown location>:-1

location: <unknown location>:-1
ERROR (bke.fcurve): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/blenkernel/intern/fcurve.c:1381 driver_get_variable_property: driver has an invalid target to use (path = (null))

Error in Driver: The following Python expression failed:
	'var + (ph_AI/3) + (ph_E/15) + (ph_U/15) + (ph_CDG/7.855) + (ph_L/6.33468)'

Traceback (most recent call last):
  File "<bpy driver>", line 1, in <module>
NameError: name 'ph_AI' is not defined

**Comment by animate1978** [comment]
https://docs.blender.org/manual/en/dev/advanced/scripting/security.html

Ok so that makes it clear, I guess about security warning. Not sure when THIS was added but it is there... I have an earlier build on Win7 as well as MB-Lab 1.7.4 and this error does not happen.

So SOMETHING happened.

**Comment by animate1978** [comment]
So further investigation reveals that when I made up the new humanoid_library.blend file that I messed up the face rig.

So I tried to correct this, the face rig gets appended BUT the rig fails AND it fails to delete now.

I am lost now I have no clue what to do here

**Comment by animate1978** [comment]
Went to an earlier version of humanoid_library.blend that works, appended only the fixed armatures, STILL have bugs!

**Comment by animate1978** [comment]
Switching to fully guarded memory allocator.
Blender 2.80 (sub 74)
Build: 2019-07-02 12:37:53 Linux Release
argv[0] = /home/farishta/blender-2.80.74/blender
argv[1] = --debug
Read prefs: /home/farishta/.config/blender/2.80/config/userpref.blend
read file /home/farishta/.config/blender/2.80/config/startup.blend
  Version 280 sub 74 date 2019-06-19 18:29 hash d30f72dfd8ac
Warning: Could not find a matching GPU name. Things may not behave as expected.
Detected OpenGL configuration:
Vendor: X.Org
Renderer: AMD TAHITI (DRM 2.50.0 / 4.15.0-54-generic, LLVM 6.0.0)
found bundled python: /home/farishta/blender-2.80.74/2.80/python
mb_lab updater verbose is enabled
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_install_popup'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_install_popup'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_check_now'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_check_now'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_update_now'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_update_now'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_update_target'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_update_target'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_install_manually'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_install_manually'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_updated_successful'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_updated_successful'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_restore_backup'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_restore_backup'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_ignore'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_ignore'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_end_background'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_end_background'>
mb_lab Updater: Read in json settings from file
Read blend: /home/farishta/MB_LAB_TESTING/fk_final.blend
read file /home/farishta/MB_LAB_TESTING/fk_final.blend
  Version 280 sub 74 date 2019-06-15 22:35 hash 87de71a8aaa0
blo_find_main: added new lib /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/data/humanoid_library.blend
read file /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/data/humanoid_library.blend
  Version 280 sub 74 date unknown hash 
Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 1841, in execute
    if not facerig.delete_face_rig():
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 209, in delete_face_rig
    bpy.ops.object.delete()
  File "/home/farishta/blender-2.80.74/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.delete.poll() failed, context is incorrect

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by animate1978** [comment]
Still getting errors related to deleting the rig.

Using Linux build 07/03/19 - 50ccbe6bb233

In conversations on Discord it was mentioned that the current Dev merged code was based off of the Blender git repository so I am going to wait a couple of days to test again, this may be related to a bug that is already fixed just not on the build bot yet.... I don't know, I will download the next builds and test this again this week.

***
terminal output
***

blo_find_main: added new lib /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/data/face_rig/face_rig_lib.blend
read file /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/data/face_rig/face_rig_lib.blend
  Version 280 sub 51 date unknown hash 
blo_find_main: found library /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/data/face_rig/face_rig_lib.blend
read file /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/data/face_rig/face_rig_lib.blend
  Version 280 sub 51 date unknown hash 
failed to removed a driver: 0
failed to removed a driver: 0
failed to removed a driver: 0
failed to removed a driver: 0
failed to removed a driver: 0
failed to removed a driver: 0
failed to removed a driver: 0
failed to removed a driver: 0
Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 1852, in execute
    if not facerig.delete_face_rig():
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/facerig.py", line 307, in delete_face_rig
    bpy.ops.object.delete()
  File "/home/farishta/blender-2.80.74/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.delete.poll() failed, context is incorrect

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by animate1978** [comment]
Still having the same bug trying to delete the rig after adding it.

***

version: 2.80 (sub 74), branch: master, commit date: 2019-07-03 19:06, hash: cc667854a94d, type: Release
build date: 2019-07-04, 01:07:30
platform: Linux

**Comment by animate1978** [comment]
OK quick update to this. Was able to delete the rig only AFTER selecting the character, with no errors....

Is there a way to delete this rig without having to select the character first?

**Comment by NumesSanguis** [comment]
Conceptual-wise we could make the `Delete Face Rig` grayed out, and only make it clickable when the character is selected. We should add a note "Select character to delete Face Rig" below it though.
If the problem is only the selection of the character.

**Comment by NumesSanguis** [comment]
Downloaded the master today, got this output when trying to delete the facerig (with FACS enabled), after creating a character with EEVEE engine and portrait studio lights (character unselected, pose mode):
```
Error: Unable to pack file, source path 'C:\Users\user\AppData\Roaming\usr\share\fonts\truetype\freefont\FreeMono.ttf' not found
Error: Unable to pack file, source path 'C:\Users\user\AppData\Roaming\usr\share\fonts\truetype\freefont\FreeMono.ttf' not found
WARN (bke.data_transfer): K:\BlenderGit\blender\source\blender\blenkernel\intern\font.c:198 vfont_get_data: Font file doesn't exist: C:\Users\user\AppData\Roaming\usr\share\fonts\truetype\freefont\FreeMono.ttf
facs_rig_slider_AU11.MBlab_bd1565450429.4944 slider controller not found
facs_rig_slider_AU13.MBlab_bd1565450429.4944 slider controller not found
facs_rig_slider_AU18.MBlab_bd1565450429.4944 slider controller not found
facs_rig_slider_AU22.MBlab_bd1565450429.4944 slider controller not found
```

Error output when trying to remove (character selected, object mode):
```
Error: failed to delete face rig
```
Nothing more :' )

**Comment by animate1978** [comment]
```
Error: Unable to pack file, source path 'C:\Users\user\AppData\Roaming\usr\share\fonts\truetype\freefont\FreeMono.ttf' not found
Error: Unable to pack file, source path 'C:\Users\user\AppData\Roaming\usr\share\fonts\truetype\freefont\FreeMono.ttf' not found
WARN (bke.data_transfer): K:\BlenderGit\blender\source\blender\blenkernel\intern\font.c:198 vfont_get_data: Font file doesn't exist: C:\Users\user\AppData\Roaming\usr\share\fonts\truetype\freefont\FreeMono.ttf
```

Hmm, I will have to look at the font thing

**Comment by amirpavlo** [comment]
I have updated the code so you don't need to have the Rig selected to delete it. My updates look like they are in the main repo. Here is a video showing the operation of adding/deleting a face rig.
https://youtu.be/7QT9lEracME

**Comment by animate1978** [comment]
So I have been going through bug reports and testing - I missed this one. It's fine. Closing now
