### ISSUE TITLE
Data Organization

### ISSUE THREAD

**Issue by telnetr4** [animate1978/MB-Lab#14]
This issue should probably be tagged "enhancement".

Let's talk data organization, mainly the current directory layout: The current way the data directory is laid out is a bit of a mess. Not too bad, but I think it needs some fixing. Before I attempt to do this, I'd like to talk about a few things and get some insight before I just pick something, change a bunch of things and then find nobody likes it as this will likely break a bunch of stuff. I'm already working on moving around global variables and better compartmentalization of code, and I feel this is the next big step.

There are two ways I can see the data directory being laid out. I will call these Library-centric and Project-centric as I am unfamiliar with whether more formal technical terms exist.

**What we have right now.**
Library-centric is what closest resembles what we have right now: one folder for each module type (anthropometry, assets, bboxes, etc) with all the module files from all figures in each folder. The exception, as far as I can tell, is the humanoid_library.blend which contains all the texture nodes, shaders, skeletons, geometry, etc. (I feel like these should be separated into their own files). Library-centric is most likely going to be the easiest to implement; There is only one root directory to worry about and all the files that need to be referenced are in it. The problem is distributing 3rd party additions (new characters) would most likely require merging and removal of said additions would either require a program or a lot of time removing files (and woe to you if said modification replaced anything).

Here is an example of what the data folder would look like as Library-centric (directory count and hierarchy is subject to change):
```
data
├───anthropometry
│   ├───hu_f_anthropometry
│   └───hu_m_anthropometry
├───assets
│   └───mblab_assets_textures
├───bboxes
├───expressions_comb
│   ├───anime_expressions
│   └───human_expressions
├───expressions_morphs
├───joints
├───measures
├───morphs
├───pgroups
├───phenotypes
│   ├───f_af01_ptypes
│   ├───f_an01_ptypes
│   ├───f_an02_ptypes
│   ├───f_as01_ptypes
│   ├───f_ca01_ptypes
│   ├───m_af01_ptypes
│   ├───m_an01_ptypes
│   ├───m_an02_ptypes
│   ├───m_as01_ptypes
│   └───m_ca01_ptypes
├───poses
│   ├───female_poses
│   ├───male_poses
│   └───rest_poses
├───presets
│   ├───anime_female_base
│   ├───anime_male_base
│   ├───human_female_anime
│   ├───human_female_base
│   ├───human_female_elf
│   ├───human_male_anime
│   ├───human_male_base
│   ├───human_male_dwarf
│   └───human_male_elf
├───textures
├───transformations
├───vertices
└───vgroups
```

Project-centric is what I think we should aim for. If you have played a computer game with modding support (Rimworld, Kerbal Space Program and Starbound come to mind) you might have some idea of what I'm talking about. Instead of everything being under the same root directory, each character and addition is in its own "project" directory. This makes it easier for debugging and loading specific characters. Removal or adding of characters and additions just requires you moving a single folder. Loading EVERYTHING as a library would take longer without preemption (I think that term fits here), however I think this could easily be solved by the addition of a project info JSON file that contains project information. MB_lab would visibly work as if all the directories for each project were merged together. While it makes the entire directory tree bigger, it makes it much easier to work with in piecemeal.

Here is an example of what the data folder would look like as Library-centric (directory count and hierarchy is subject to change):

```
data
├───hu_base_female
│   ├───anthropometry
│   ├───assets
│   ├───expressions_comb
│   ├───expressions_morphs
│   ├───joints
│   ├───measures
│   ├───morphs
│   ├───pgroups
│   ├───phenotypes
│   │   ├───f_af01_ptypes
│   │   ├───f_as01_ptypes
│   │   └───f_ca01_ptypes
│   ├───poses
│   │   └───rest_poses
│   ├───presets
│   │   ├───human_female_base
│   │   └───human_female_elf
│   ├───textures
│   ├───transformations
│   ├───vertices
│   └───vgroups
├───hu_base_male
│   ├───anthropometry
│   ├───assets
│   ├───expressions_comb
│   ├───expressions_morphs
│   ├───joints
│   ├───measures
│   ├───morphs
│   ├───pgroups
│   ├───phenotypes
│   │   ├───m_af01_ptypes
│   │   ├───m_as01_ptypes
│   │   └───m_ca01_ptypes
│   ├───poses
│   │   └───rest_poses
│   ├───presets
│   │   ├───human_male_base
│   │   └───human_male_elf
│   ├───textures
│   ├───transformations
│   ├───vertices
│   └───vgroups
├───human_male_dwarf
│   └───presets
│       └───human_male_dwarf
├───hu_female_anime
│   ├───assets
│   ├───expressions_comb
│   ├───expressions_morphs
│   ├───joints
│   ├───measures
│   ├───morphs
│   ├───pgroups
│   ├───phenotypes
│   │   ├───f_an01_ptypes
│   │   └───f_an02_ptypes
│   ├───poses
│   ├───presets
│   │   └───human_female_anime
│   ├───textures
│   ├───transformations
│   ├───vertices
│   └───vgroups
├───hu_male_anime
│   ├───assets
│   ├───expressions_comb
│   ├───expressions_morphs
│   ├───joints
│   ├───measures
│   ├───morphs
│   ├───pgroups
│   ├───phenotypes
│   │   ├───m_an01_ptypes
│   │   └───m_an02_ptypes
│   ├───poses
│   ├───presets
│   │   └───human_male_anime
│   ├───textures
│   ├───transformations
│   ├───vertices
│   └───vgroups
```

I think starting with a Library-centric model while marking out parts we identify as needing to be changed when switching to a Project-centric organization once we nail down the specifics.

**Comment by animate1978** [comment]
I like this idea. I agree the directory structure is a bit of a mess. How you described the change is great and I think in the end will make editing, adding or removing files, characters etc... would be easier with this new layout. This also makes it easier for users to do some editing themselves if they wanted to without having to really go through the entire directory tree just to edit one thing, for instance. For us it would make changes so much easier to work with I think.

Very nice!

**Comment by animate1978** [comment]
I just checked out the algorithms.py, which is where MB-Lab reads the data path. This is where it reads the character_config.json file and the humanoid_library.blend file. If we were to separate each character type into it's own blend file it would require some serious coding, beyond my scope I think.

https://github.com/animate1978/MB-Lab/blob/d7719d85294c2edea77b7dd3d8c5663d3c93756c/algorithms.py#L48

I think some of the changes could be done but as far as the humanoid_library.blend file, that still would have to remain the same in order for MB-Lab to function

**Comment by telnetr4** [comment]
@animate1978 That's effectively just a directory check. At least, that's what it now is after I made a global variable for data_path.

I don't think it would be too hard. The way I'm going to do it is store a dictionary with the keys being valid folder names and the values being lists that have all the information for all the contents for each of these folders. Not sure if this is the most efficient way to do it, but I'll start with it.

**Comment by NumesSanguis** [comment]
Maybe a mix of 2 ways you suggest @telnetr4 would be better.
For example `data/expressions_comb/human_expressions/` is for any human base model the same. Adding a facial expression would become difficult and error prone if a model is forgotten. Also, it would result in file duplication, since you'll be copy pasting the same file without modification.

That would result in something like:

    data
    ├───hu_base
        ├───expressions_comb
        ├───hu_base_female
        │   ├───anthropometry
        ├───hu_base_male
        │   ├───anthropometry
    ├───hu_anime
        ├───expressions_comb
        ├───hu_base_female
        │   ├───anthropometry
        ├───hu_base_male
        │   ├───anthropometry

In this structure, all humans will have access to the same expressions (preventing data duplication), but since anthropometry is different by gender, this is in a deeper level.

**Comment by animate1978** [comment]
Ah ok.

**Comment by telnetr4** [comment]
That is something else we should consider: how to deal with inheriting assets from other projects.

**Comment by blaisefaint** [comment]
Speaking of other projects, I'm curious if anyone has looked at MakeHuman-Community v1.20a, as they have added some community features that make it easier to add clothes, hair, and other assets to characters.

**Comment by animate1978** [comment]
![makehuman_asset_vs_mblab](https://user-images.githubusercontent.com/479115/50736240-9aac9b00-1180-11e9-98bb-2977c354c13e.png)

Just a slight problem with the assets from MakeHuman, they are not to scale with MB-Lab characters. However with some work they can be adopted.

**Comment by animate1978** [comment]
![makehuman_asset_vs_mblab002](https://user-images.githubusercontent.com/479115/50736421-03951280-1183-11e9-99d6-a164b5c4938f.png)

Example of scaling, went down to .9 on XYZ scale but it works

**Comment by NumesSanguis** [comment]
So fast, amazing! Don't overwork yourself though.

**Comment by telnetr4** [comment]
I'm currently working on making 1.6.5b work with my new system, as I'm most familiar with this version.

Should I switch to working on Blender 2.7.0 or should I just merge it after I finish figuring it out?

**Comment by telnetr4** [comment]
This is a preview of the file organization I'm working with, with the base human and anime humans split into two separate projects (mainly so I can test out the "merging" system)
```
data
├───Anime
│   │   characters_config.json
│   │   humanoid_library.blend
│   │   info.json
│   │   retarget_knowledge.json
│   │
│   ├───assets
│   │       hair01_anime_female.blend
│   │       hair01_anime_male.blend
│   │
│   ├───bboxes
│   │       anime_female_bbox.json
│   │       anime_male_bbox.json
│   │
│   ├───expressions_comb
│   │   └───anime_expressions
│   │           angry01.json
│   │           annoyed01.json
.....
│   │           very_sad01.json
│   │           wink01.json
│   │
│   ├───expressions_morphs
│   │       f_an01_exprs.json
│   │       f_an02_exprs.json
│   │       f_an03_exprs.json
│   │       m_an01_exprs.json
│   │       m_an02_exprs.json
│   │       m_an03_exprs.json
│   │
│   ├───joints
│   │       anime_female_joints.json
│   │       anime_male_joints.json
│   │
│   ├───morphs
│   │       anime_female_morphs.json
│   │       anime_male_morphs.json
│   │       m_an01_morphs.json
│   │       m_an02_morphs.json
│   │       m_an03_morphs.json
│   │       m_an03_morphs_extra.json
│   │
│   ├───pgroups
│   │       anime_female_polygs.json
│   │       anime_male_polygs.json
│   │
│   ├───phenotypes
│   │   ├───f_an01_ptypes
│   │   │       african.json
│   │   │       asian.json
│   │   │       caucasian.json
│   │   │
│   │   ├───f_an02_ptypes
│   │   │       african.json
│   │   │       asian.json
│   │   │       caucasian.json
│   │   │
│   │   ├───m_an01_ptypes
│   │   │       african.json
│   │   │       asian.json
│   │   │       caucasian.json
│   │   │
│   │   └───m_an02_ptypes
│   │           african.json
│   │           asian.json
│   │           caucasian.json
│   │
│   ├───presets
│   │   ├───anime_female_base
│   │   │       anyme_style1.json
│   │   │       anyme_style2.json
│   │   │       anyme_style3.json
│   │   │       specialtype_bodybuilder.json
│   │   │       specialtype_obese.json
│   │   │
│   │   └───anime_male_base
│   │           anyme_style1.json
│   │           anyme_style2.json
│   │           anyme_style3.json
│   │           specialtype_bodybuilder.json
│   │           specialtype_obese.json
│   │
│   ├───textures
│   │       anime_female_diffuse.png
│   │       anime_male_diffuse.png
│   │
│   ├───transformations
│   │       anime_female_base_transf.json
│   │       anime_male_base_transf.json
│   │
│   ├───vertices
│   │       f_an01_verts.json
│   │       f_an02_verts.json
│   │       f_an03_verts.json
│   │       m_an01_verts.json
│   │       m_an02_verts.json
│   │       m_an03_verts.json
│   │
│   └───vgroups
│           anime_female_vgroups_base.json
│           anime_male_vgroups_base.json
│
└───Core
    │   characters_config.json
    │   humanoid_library.blend
    │   info.json
    │   retarget_knowledge.json
    │
    ├───anthropometry
    │   ├───hu_f_anthropometry
    │   │       0000_0.json
    │   │       0000_25.json
.....
    │   │       2200_5.json
    │   │       2200_75.json
    │   │       2201_0.json
    │   │
    │   └───hu_m_anthropometry
    │           000.json
    │           001.json
.....
    │           100.json
    │           101.json
    │
    ├───assets
    │   │   hair01_human_female.blend
    │   │   hair01_human_male.blend
    │   │
    │   └───mblab_assets_textures
    │           h_f_hair01_alpha.png
    │           h_f_hair01_refl.png
    │           h_f_hair01_tone.png
    │           h_m_hair01_alpha.png
    │           h_m_hair01_refl.png
    │           h_m_hair01_tone.png
    │
    ├───bboxes
    │       human_female_bbox.json
    │       human_male_bbox.json
    │
    ├───expressions_comb
    │   └───human_expressions
    │           angry01.json
    │           annoyed01.json
.....
    │           very_sad01.json
    │           wink01.json
    │
    ├───expressions_morphs
    │       f_af01_exprs.json
    │       f_as01_exprs.json
    │       f_ca01_exprs.json
    │       f_ft01_exprs.json
    │       m_af01_exprs.json
    │       m_as01_exprs.json
    │       m_ca01_exprs.json
    │       m_ft01_exprs.json
    │       m_ft02_exprs.json
    │
    ├───joints
    │       human_female_joints.json
    │       human_female_joints_offset.json
    │       human_male_joints.json
    │       human_male_joints_offset.json
    │
    ├───measures
    │       human_female_measures.json
    │       human_male_measures.json
    │
    ├───morphs
    │       f_af01_morphs.json
    │       f_as01_morphs.json
.....
    │       m_ft02_morphs.json
    │       m_ft02_morphs_extra.json
    │
    ├───pgroups
    │       human_female_polygs.json
    │       human_male_polygs.json
    │
    ├───phenotypes
    │   ├───f_af01_ptypes
    │   │       aboriginal.json
    │   │       african.json
    │   │       afroasian.json
    │   │       afromediterranean.json
    │   │
    │   ├───f_as01_ptypes
    │   │       central_american.json
    │   │       central_asian.json
    │   │       east_asian.json
    │   │       north_american.json
    │   │       north_asian.json
    │   │       south_asian.json
    │   │
    │   ├───f_ca01_ptypes
    │   │       afrocaucasian.json
    │   │       central_european.json
    │   │       east_european.json
    │   │       euroartic.json
    │   │       euromediterranean.json
    │   │       northwest_european.json
    │   │       north_european.json
    │   │       west_asian.json
    │   │
    │   ├───m_af01_ptypes
    │   │       aboriginal.json
    │   │       african.json
    │   │       afroasian.json
    │   │       afromediterranean.json
    │   │
    │   ├───m_as01_ptypes
    │   │       central_american.json
    │   │       central_asian.json
    │   │       east_asian.json
    │   │       north_american.json
    │   │       north_asian.json
    │   │       south_asian.json
    │   │
    │   └───m_ca01_ptypes
    │           afrocaucasian.json
    │           central_european.json
    │           east_european.json
    │           euroartic.json
    │           euromediterranean.json
    │           northwest_european.json
    │           north_european.json
    │           west_asian.json
    │
    ├───poses
    │   ├───female_poses
    │   │       captured01.json
    │   │       flying01.json
.....
    │   │       standing_old_people.json
    │   │       standing_symmetric.json
    │   │
    │   ├───male_poses
    │   │       captured01.json
    │   │       evil_beast.json
.....
    │   │       standing_old_people.json
    │   │       standing_symmetric.json
    │   │
    │   └───rest_poses
    │           a-pose.json
    │           ii-pose.json
    │           lambda-pose.json
    │           star-pose.json
    │           t-pose.json
    │
    ├───presets
    │   ├───human_female_anime
    │   │       type_athletic.json
    │   │       type_extreme_bodybuilder.json
.....
    │   │       type_triangle01.json
    │   │       type_vigorous01.json
    │   │
    │   ├───human_female_base
    │   │       specialtype_hero01.json
    │   │       specialtype_hero02.json
.....
    │   │       type_triangle02.json
    │   │       type_vigorous01.json
    │   │
    │   ├───human_female_elf
    │   │       specialtype_hero01.json
    │   │       specialtype_hero02.json
......
    │   │       type_triangle02.json
    │   │       type_vigorous01.json
    │   │
    │   ├───human_male_anime
    │   │       specialtype_brute.json
    │   │       specialtype_evil_genius.json
.....
    │   │       type_stocky02.json
    │   │       type_vigorous01.json
    │   │
    │   ├───human_male_base
    │   │       specialtype_brute.json
    │   │       specialtype_evil_genius.json
.....
    │   │       type_stocky02.json
    │   │       type_vigorous01.json
    │   │
    │   ├───human_male_dwarf
    │   │       specialtype_brute.json
    │   │       specialtype_evil_genius.json
.....
    │   │       type_stocky02.json
    │   │       type_vigorous01.json
    │   │
    │   └───human_male_elf
    │           specialtype_brute.json
    │           specialtype_evil_genius.json
.....
    │           type_stocky02.json
    │           type_vigorous01.json
    │
    ├───textures
    │       human_female_diffuse.png
    │       human_female_displacement.png
.....
    │       human_male_specular.png
    │       human_male_subdermal.png
    │
    ├───transformations
    │       human_female_anime_transf.json
    │       human_female_base_transf.json
    │       human_female_elf_transf.json
    │       human_male_anime_transf.json
    │       human_male_base_transf.json
    │       human_male_dwarf_transf.json
    │       human_male_elf_transf.json
    │
    ├───vertices
    │       f_af01_verts.json
    │       f_as01_verts.json
    │       f_ca01_verts.json
    │       f_ft01_verts.json
    │       m_af01_verts.json
    │       m_as01_verts.json
    │       m_ca01_verts.json
    │       m_ft01_verts.json
    │       m_ft02_verts.json
    │
    └───vgroups
            human_female_vgroups_base.json
            human_female_vgroups_muscles.json
            human_male_vgroups_base.json
            human_male_vgroups_muscles.json
```
Note the added info.json.

**Comment by animate1978** [comment]
I like it. This way if / when we start making a new character model it will be easier to add, I think.

**Comment by telnetr4** [comment]
You may want to label this as "Help Wanted."

**Comment by animate1978** [comment]
I am closing this issue because with the recent additions of MB-Dev, I believe this has been solved in a way...
