### ISSUE TITLE
Eye Shader improvements

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#146]
So Amir and I have been working on the eyeball and iris shaders.

So far the shaders have a mix between procedural and texture map networks. They have Principled BSDF shader nodes.

The skin Editor has been updated as well to include the following

- Eye SSS
- Eye Iris Mix
- Eye Shader Mix
- Eye Vein Amount
- Hue Saturation and Value

Cycles
![new_eyes_01](https://user-images.githubusercontent.com/479115/61174968-67065f80-a56d-11e9-82e3-61b84c4c6f83.png)

EEVEE
![new_eyes_02](https://user-images.githubusercontent.com/479115/61174969-67065f80-a56d-11e9-988d-dedefc3c2afd.png)

**Comment by animate1978** [comment]
![new_eyeball_shader_preview](https://user-images.githubusercontent.com/479115/61175482-d1bb9900-a575-11e9-8234-211126bc3b93.png)

**Comment by animate1978** [comment]
The eyeball shader needs work. Currently the SSS doesn't work well between the two different shading networks.

Removed the input for Eye SSS, as mentioned above it was not working well between the two networks, so the SSS are hard coded now to 0.01 in both networks.

**Comment by animate1978** [comment]
Having even more issues, primarily with the SSS again.

It is weird behavior, when switching from the texture network to the procedural, the SSS will not function???

I am thinking, especially with how awful the procedural eyeball looks, that I may just end up deleting that whole concept and just have straight up texture map.

**Comment by animate1978** [comment]
Just to be clear this is for the eyeball shader only, the iris shader is perfectly fine.

**Comment by animate1978** [comment]
![new_eyes_EEVEE_01](https://user-images.githubusercontent.com/479115/61376205-5bb17d80-a866-11e9-815b-e7a5008b9732.png)

Final look of the eyeball shader

![new_eyeball_shader_preview_02](https://user-images.githubusercontent.com/479115/61376230-69ff9980-a866-11e9-92e4-7cbddbcd983b.png)

Demo of improved eyeball and iris, in cycles viewport 32 samples

**Comment by NumesSanguis** [comment]
If the shader is buggy, maybe comment out the code, but it could be a good starting point if someone thinks he/she knows a good way to implement procedural shaders for the eyeballs.

Is the "Final look of the eyeball shader" the bug or after the bug fix? Because too me it's a bit too white.

**Comment by animate1978** [comment]
The procedural elements are still there in the nodes, just not connected to anything at the moment, still actively trying to get a good look.

I think it was how the nodes were connected to each other with the mix of the SSS canceling each other out, what needs to happen is just use a common shading network.
