### ISSUE TITLE
Crash on Activate

### ISSUE THREAD

**Issue by salavine1** [animate1978/MB-Lab#147]
Hello
Running macOS Mojave version 10.14.5
Blender 2.80.0 RC

After installing and trying to activate I get this error.

![2019-07-14_13-15-42](https://user-images.githubusercontent.com/7305394/61187634-a13d3300-a639-11e9-999c-0c63b0f784e3.png)

**Comment by animate1978** [comment]
We've had a LOT of issues involving MacOS

We are investigating

**Comment by animate1978** [comment]
Sorry for the late response.

It seems, from looking at the screenshot (and the fact I don't have a Mac), you might not have numpy installed in your Python installation. Not sure why.

Try this - https://stackoverflow.com/a/37532831

**Comment by mklemarczyk** [comment]
Hello, can I ask you @salavine1 to check if problem exists with latest Blender and MB-Lab versions?

**Comment by animate1978** [comment]
Closing this issue
