### ISSUE TITLE
Error when trying to click the checkbox to start

### ISSUE THREAD

**Issue by stickysubmerge** [animate1978/MB-Lab#148]
windows 10

blender 2.79

![Untitled](https://user-images.githubusercontent.com/52898678/61191709-2abd2700-a673-11e9-9c2d-15c23a6be525.png)

**Comment by animate1978** [comment]
MB-Lab is for Blender 2.80, the last version we made for Blender 2.79 is here - 

https://github.com/animate1978/MB-Lab/releases/tag/1.6.5b
