### ISSUE TITLE
How to install 1.65?

### ISSUE THREAD

**Issue by millionart** [animate1978/MB-Lab#15]
My blender version is 2.79, I can use 1.61, but I can't install 1.65 download from Projects page. 
Nothing happens after loading the addons zip.

**Comment by millionart** [comment]
I did step 123, but I can't find the category named "Characters".

**Comment by animate1978** [comment]
That is very strange. Do you get any error messages in Blender?

Depending on the OS you should have a hidden folder in your user directory that contains the addon, not sure if you have removed any old versions first, that is very important as it will cause conflicts but try downloading a clone ZIP of the current MB-Lab project and repeat installation.

**Comment by millionart** [comment]
I emptied that folder (Blender Foundation\Blender\2.79\scripts\addons) and repeated step 123. MB-Lab-1.6.5b appears in this folder, but blender is still no category named "Characters".

**Comment by millionart** [comment]
I successfully reinstalled 1.61, but 1.65 still can't be installed.

**Comment by animate1978** [comment]
Well that is depressing. Looks like I am going to have to boot up my Windows laptop and see if I get the same problem.

Are you using the release version of Blender 2.79 or is it a custom build, or a recent nightly build?

**Comment by millionart** [comment]
Both tested.

**Comment by millionart** [comment]
I can continue to use 1.61, I hope this problem can be solved smoothly, thanks for your work.

**Comment by millionart** [comment]
No, there is no MB-Lab at all in the list.

**Comment by chickenproductions** [comment]
ive been getting this problem as well for some reason and im not sure why

**Comment by chickenproductions** [comment]
ok apparently downloading it directly instead of downloading it from the releases page appeared to work for me

**Comment by animate1978** [comment]
That is strange. Could it be possibly be how the archive file is named from the release page?

**Comment by millionart** [comment]
It works, thank you.

**Comment by animate1978** [comment]
Very good, sorry it took so long to figure something out that was so simple in the end.
