### ISSUE TITLE
Skin Shader Rework

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#155]
**Is your feature request related to a problem? Please describe.**
The problem is that the current skin shader is too dependent on image maps for simple functions, such as SSS, specular and roughness. The current skin shader looks a bit off, which is my fault, so the idea is to replace the skin shader with a more accurate shader.

Version 2 of the skin shader would be based off a shader that user @whyoh submitted months ago. This uses a more accurate skin shading model, uses more masks to drive procedural elements. Right now the prototype is a basic implementation of what this will end up as.

**Describe alternatives you've considered**
I've looked at other skin shaders, some of which are decent, others not so much. The prototype model seems to work very well so far.

**Additional context**

![mblab_skin_ver2_cycles_001](https://user-images.githubusercontent.com/479115/62470078-3f1aae00-b75f-11e9-9e40-9ee2fef54551.png)

**Comment by animate1978** [comment]
![mblab_skin_ver2_cycles_002](https://user-images.githubusercontent.com/479115/62477255-38476780-b76e-11e9-9943-23c399562a89.png)

Another preview

![skin_render_01](https://user-images.githubusercontent.com/479115/62477406-88bec500-b76e-11e9-803b-5e96ebbe6185.png)

One of the things about the SSS in this model is that it uses a thickness map so there is no fading on the fingers or toes, for instance, with the current model in 1.7.5 and previous versions.

![old_shading_mod_SSS_01](https://user-images.githubusercontent.com/479115/62478302-59a95300-b770-11e9-8e7c-50581e3e861d.png)
Above for example is the current 1.7.5 shading model

![new_shading_mod_SSS_01](https://user-images.githubusercontent.com/479115/62479701-a9d5e480-b773-11e9-93df-b0d644f487d9.png)
Above is the new shading model in the prototype shader.

Still needs some work, with the veins and freckles (which I recently have been working on). Still not sure when this new shading model will be committed to the repo, I still need to work on the map nodes in the shader (currently the masks are packed into the dev file which is not conducive to MB-Lab's workflow) so this is still very much a prototype on my end.

Hopefully by the end of the week this new shader (and the other edits I have done) will appear in the Dev branch.

**Comment by animate1978** [comment]
Have a basic implementation of this shader working with the Female models so far, with new tone maps (which really need work but the idea is there).

So by the end of the weekend it should be functional across the board.

**Comment by NumesSanguis** [comment]
Looks nice :)
I would make the eyes a little bit less red, and I think the lips could use a bit more gloss:
Lips: https://www.videoblocks.com/video/extreme-close-up-of-lips-18-year-old-girl-with-smile-without-lipstick-scoqqeoimv1d6uk

**Comment by animate1978** [comment]
I agree. I think the SSS is affecting the eyes so that needs work. The skin oil will also be adjusted, it's going to be based off of a mask so it will use grey scale values for glossiness
