### ISSUE TITLE
eye shader repeats. More visible on dark complexion.

### ISSUE THREAD

**Issue by CodeDoes** [animate1978/MB-Lab#162]
**To Reproduce**
Make a character. change the skin complexion to 1

**Screenshots**
![Annotation 2019-09-28 205517](https://user-images.githubusercontent.com/20872701/65821164-4d062000-e232-11e9-92f9-11b2607ddf7b.png)
![Annotation 2019-09-28 205514](https://user-images.githubusercontent.com/20872701/65821165-4d9eb680-e232-11e9-8197-89ccfe68dd1a.png)

**Comment by animate1978** [comment]
Working on this and should be committed later tonight or tomorrow.

**Comment by animate1978** [comment]
![eyes_fix_001](https://user-images.githubusercontent.com/479115/65934881-a3af5d80-e3dc-11e9-8953-7828cbbdae91.png)

**Comment by animate1978** [comment]
This has been fixed for MB-Lab 1.7.6
