### ISSUE TITLE
vertex groups for procedural hairs

### ISSUE THREAD

**Issue by dribeiro73rj** [animate1978/MB-Lab#169]
**Is your feature request related to a problem? Please describe.**

create hairstyles in a mb-lab character demands to create 3 vector groups each time

**Describe the solution you'd like**

I would like a good set of vertex groups, even related hair particle systems on each of them

**Describe alternatives you've considered**
add at least 3 vertex groups on the base models for procedural hair :

top - the top scalp
side - the side scalp
back - the back scalp

Additional context**

![image](https://user-images.githubusercontent.com/53482482/68070439-033ab900-fd4d-11e9-9429-3d080a64a524.png)

**Comment by Noizirom** [comment]
Within the next week I'm going to try to upload the scripts for my fork. I
have a rotation limits for bones and polygon maps for hair. I just need to
transfer the script into mb_lab.

**Comment by animate1978** [comment]
![FINAL_TEST_002](https://user-images.githubusercontent.com/479115/68085030-73a31200-fe01-11e9-8d03-f7161e6e5c92.png)

Initial testing and viewport rendering done after merging the Hair Engine into the Developmental branch

**Comment by animate1978** [comment]
@Noizirom is there a way to attach the generated Hair object to the MB-Lab character? As a test I moved the character, the hair remains in place.

I know that we can parent it to the mesh, how hard would it be to do this in the code?

**Comment by Noizirom** [comment]
I'll have to test it again. Currently it should follow the head in pose. It
has an Armature mod, but I can test parenting also. I'll look at it
tonight. Let you know by tomorrow.

**Comment by animate1978** [comment]
Ah ok. It does in move in Pose mode, I am just concerned that when / if users move the character, lets say an animation, and the body (actually in this case the armature) moves in Object mode, then the Hair object remains in place.

**Comment by Noizirom** [comment]
I corrected the parenting. It is now patented to the armature. I also added
a button to add hair to selected polygons. I will be uploading in a hour or
so. The hairs can be added anywhere, but I suggested only adding hair to
the head. Its the only way it will work properly, but anywhere else will
need the targets changed manually. And you can still used the head hair
with it. Also, you can now add as many head hair or loose hairs as you
want. But I strongly recommend just adding facial hair. And btw, these
haven't been tested with shapekeys.
I'll post something after I update the scripts on github. I'm just not by
the computer at the moment.

**Comment by Noizirom** [comment]
The “Add Hair” button is now the “Particle Hair” button. Both can be found
as the last items in the “ASSETS LIBRARY” menu.


Select the body mesh.


Go into “EDIT' mode and select the desired polygons.

WARNING! Any polygon can be selected, but it is recommended to on select
polygons in the head.


Switch back to “OBJECT” mode and press the “Hair from Selected” Button.

Adjust and Groom the Hair.

The “Particle Hair” button still can be used with selected polygons hair.


You can add an unlimited amount of hair objects.

**Comment by animate1978** [comment]
@Noizirom I hate to report but the Latino male nor female do not have JSON hair export associated. I know that you have translated these to npz, but this is an example of using JSON over npz, I can add the Latino JSON right now, as opposed to the npz (mainly because I am not sure the workflow).

Something to think about before we make a commitment to a binary file

**Comment by Noizirom** [comment]
If you have a list of the polygon indexes, I can give you a script to
update the .npz or I could update them myself. I will get the script to you
later.  I've been making node setters and getters for the EEVEE hair
shader. I should have something within the next week for EEVEE.

**Comment by animate1978** [comment]
This is long overdue to be closed
