### ISSUE TITLE
vertices influence broken in 2.80 if using basic muscle armature system

### ISSUE THREAD

**Issue by gitnob** [animate1978/MB-Lab#20]
Create a new figure with basic muscle armature system turned on. Finalize it.
Go to modifier tab of the mesh. Switch off the armature's visibility in the viewport and switch it on again.

Mesh is totally broken after that action.

I used an actual git pull of blender 2.80 from 30.12.2018.

If you are not using the muscle system everything works fine.

In 2.79 the muscle system works also fine.

**Comment by animate1978** [comment]
![screenshot_2018-12-30_08-59-57](https://user-images.githubusercontent.com/479115/50548403-83662e80-0c11-11e9-8553-802c61e066ab.png)

Was able to reproduce this. Pretty bad bug.

**Comment by animate1978** [comment]
I updated my copy of Blender 2.80 to the latest build. This bug persists.

It also crashes Blender if you try to turn on viewport rendering in Cycles.

**Comment by gitnob** [comment]
It might be a bug within blender. I tested a simplified model (attached).
Different actions lead to a broken mesh in the viewport...
- tab into edit mode and back
- switch off and on the view of the armature modifier
- switch from layout to sculpt mode
- switch off and on subdivision modifier
- ....

after that the mesh is corrupted in the view.
getting it back: selecting the armature, change to pose mode, ...
... select another bone
... r/g/s the selected bone
brings back the correct deformed mesh.

I reduced the vertex groups down to 3 deforming groups, the problem still appears. But if I reduce to 2 vertex groups, the viewport collapsing of the mesh vanished.

Might be really a blender bug.


[simpleRig.zip](https://github.com/animate1978/MB-Lab/files/2719242/simpleRig.zip)

**Comment by gitnob** [comment]
I just did some experiments with armature and bendy bones.
I can reproduce the error with the following file. It seems to be a bendy bones problem.
Same behaviour appears as with the human mesh as soon as the bendy bones have 2 or more segments.
[bendyBonesBug.zip](https://github.com/animate1978/MB-Lab/files/2719248/bendyBonesBug.zip)

**Comment by gitnob** [comment]
animate1978, good news.
This glitch seems to be blender related.
If you keep the armature in pose mode after changing bone rotations, there is no glitching.
See also https://developer.blender.org/T60034 for more information.
I think, it's not a MBLab bug.

**Comment by animate1978** [comment]
I reopened this because the bug persists even if it is a Blender bug

**Comment by animate1978** [comment]
https://developer.blender.org/T60034

According to this the bug has been fixed.

Tested with a brand new build and yes it is fixed finally!
