### ISSUE TITLE
Removing Portrait Studio Light artifacts in Eevee

### ISSUE THREAD

**Issue by vMimas** [animate1978/MB-Lab#200]
Bright light spots appear under the nostrils when using the portrait studio light set in Eevee. Enabling "contact shadows" on each of the lights would remove these artifacts (option found under the lights' settings on properties panel). Ignore this statement if they were intentionally left disabled for performance reasons.

**Comment by animate1978** [comment]
![eevee_lights_dev_01](https://user-images.githubusercontent.com/479115/69007739-3a8d9600-0907-11ea-8b80-541ce8a43305.png)

Default settings above

![eevee_lights_dev_02](https://user-images.githubusercontent.com/479115/69007743-4aa57580-0907-11ea-8ae1-3bde61725159.png)

With Contact Shadows on

To be honest, it never even occurred to me to enable this. There is a performance issue, at least on my own system but not enough to totally dismiss this. Will consider for next release.

**Comment by animate1978** [comment]
This has been implemented in 1.7.7
