### ISSUE TITLE
Errors in docs/license.rst and website license page

### ISSUE THREAD

**Issue by josator** [animate1978/MB-Lab#205]
**Describe the bug**
File "docs/license.rst" does not contain the updated text of the current license found in "/license.txt".

For example, information about the creative commons license CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/) attributed to Manuel Bastioni option for assets generated by the tool is missing.

This also happens in the following website:

 https://mb-lab.readthedocs.io/en/latest/license.html

Which is quite misleading as it talks about a dual license but only one of the two licenses is described.

**Comment by animate1978** [comment]
This will be corrected.

**Comment by animate1978** [comment]
The new docs are located here:

https://mb-lab-docs.readthedocs.io/en/latest/license.html

**Comment by josator** [comment]
Ok thx, at least now it is clear that i can not use the tool.
