### ISSUE TITLE
Can't generate character from development branch

### ISSUE THREAD

**Issue by econundrum** [animate1978/MB-Lab#206]
**Describe the bug**

If you clone the dev repository and attempt to generate a character using it you get the below error: It's been this way for some time. I have a copy of the dev branch since just after the first version of the hair engine went in but all later versions crash when trying to make a new character.

Just looks like a basic python bug related to referencing something before you've assigned it a value.

I know it's a dev branch but since I've seen nothing about this, just in case you aren't aware I thought I'd raise it.

![MB-bug](https://user-images.githubusercontent.com/18396176/69923035-4fd2fa80-1499-11ea-85ab-7bce1457e891.png)

**To Reproduce**
1. Clone the dev branch
2. install and enable it in blender
3.Select any template or options
4. Click the generate button.

**Expected behavior**
A new character is generated.

**Additional context**
The clone I made on 7th of November does not contain this bug, 

**Logs**
`To format it correctly, logs should go in between these:`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.

**Comment by animate1978** [comment]
This must be related to the Git Large File Storage.

There was a discussion on using LFS for the repo, I think this was a mistake, as it causes problems with downloads and unless you HAVE Git LFS installed on your end then the objects that are stored in the LFS storage are not donwloaded, instead some placeholder file is added which contains nothing.
I do have to apologize I did not think this would cause issues but it is. I will be going through the appropriate docs to reverse this.

For now it is advised NOT to clone the dev branch.

**Comment by econundrum** [comment]
No problem, just wanted to ensure you where aware of this.

**Comment by animate1978** [comment]
Had to do some git surgery this morning. This should not be an issue any longer
