### ISSUE TITLE
MB_Lab_1_7_7.zip does not install/work.

### ISSUE THREAD

**Issue by Johnny1000** [animate1978/MB-Lab#211]
Greetings,
the zip file downloaded from https://mblab.dev/download/ does not install/work.
It seems to be missing an addon directory as the top directory containing all the MB-Lab files.
In stead of installing all the "loose" addon files directly into /home/username/.config/blender/2.81/scripts/addons/ it should install them to /home/username/.config/blender/2.81/scripts/addons/MB-Lab/ (or whatever you want to call your MB-Lab addon directory).
Best regards :o)
Johnny :o)

**Comment by animate1978** [comment]
I made a mistake when packing the ZIP, ack! Yes you are correct and I have updated this ZIP file to fix this, thank you for the issue report.

**Comment by Johnny1000** [comment]
Now it installs properly :o)
Thank you for a fast solution.
Keep up the good work.
Best regards :o)
Johnny :o)
