### ISSUE TITLE
Face Rig creation process fails with error message

### ISSUE THREAD

**Issue by Johnny1000** [animate1978/MB-Lab#213]
Greetings :o)

blender 2.81.16 downloaded from blender.org
MBLab 1.7.7 downloaded from mblab.dev

When trying to "Create face rig" MBLab fails with this message in the console:

`/home/username/.config/blender/2.81/scripts/addons/MB-Lab/data/face_rig/face_rig_lib.blend not found. Might need to reinstall ManuelBastioniLab`
`Error: Face Rig creation process failed`

face_rig_lib.blend does not seem to be in MB-Lab_1_7_7.zip

Best regards :o)
Johnny :o)

**Comment by animate1978** [comment]
I updated both the repository and website with the Face Rig data, this was deleted during the data wipe a week ago and was never added back in by mistake.

It is considered 1.7.7 b there is a new option to remove censors as well

**Comment by Johnny1000** [comment]
Error fixed. Thank you for a fast fix :o)
Now both the face rig and the phoneme rig works again.
Keep up the good work :o)
Best regards
Johnny :o)
