### ISSUE TITLE
Installing MB-Lab

### ISSUE THREAD

**Issue by yojikuma** [animate1978/MB-Lab#225]
I am using Blender 2.81, and tried installing 1.7.7, using the install instructions in the manual. It copied the Zip to the Users/ blender/addon file and didn't show up in the Addon categories. I manualy unzipped it, and installed the lowest folder to the user... addon file and it appears in the addon categories, but it won't let me enable it. I click the check box and it does nothing. 
please e-mail me how to install MB-lab
yojikuma2b@gmail.com

**Comment by animate1978** [comment]
I have sent an email.

Did that fix the issue? If so I can close this?

**Comment by yojikuma** [comment]
The Issue is fixed.

**Comment by reddykatam** [comment]
Hi same issue here please send me the instructions  to reddy.katam@gmail.com
Thank you very much in advance

**Comment by yojikuma** [comment]
It took me about a dozen times to finally get the full download,but once I
had it, it installed easily in blender 2.81 going to edit, preferences,
addons, then installing it from file. There is no need to unzip it. I guess
the trick is getting the full zip file. I thought the problem was on my
end. sorry I can't e-mail you a copy.
