### ISSUE TITLE
Skin Material Nodes Simplification

### ISSUE THREAD

**Issue by torridgristle** [animate1978/MB-Lab#231]
There's some nodes or node groups that scale vectors by using separate xyz, 3 math nodes, and a combine xyz. The vector math node has a scale function now so you can do all this in one node and clean up the material layout.

**Comment by animate1978** [comment]
I had not noticed this node, I will have to do some testing with it.

This node group was developed back when MB-Lab was still on Blender 2.79. Based off a tutorial found online.

**Comment by animate1978** [comment]
I have done testing with it and the next release version will have the Vector Math node.
