### ISSUE TITLE
Small bug in file_ops.py

### ISSUE THREAD

**Issue by TetoTheSquirrelFox** [animate1978/MB-Lab#233]
**Describe the bug**
A class method won't work as intended I think

**To Reproduce**
Open file_ops.py
Method def json_booleans_to_python(value) (line 278)

**Expected behavior**
When value is 0, return False, True otherwise.

**Screenshots**
![image](https://user-images.githubusercontent.com/59537161/73393635-51277480-42dc-11ea-99d9-45396ab15aa2.png)

**The bug itself**
I think that to work properly, the method should be:
```Python
def json_booleans_to_python(value):
    return value != 0
```
The method seems to be unused, but well...

**Comment by animate1978** [comment]
I will look into it

**Comment by animate1978** [comment]
I don't even think this is used anywhere in the code...

**Comment by TetoTheSquirrelFox** [comment]
I don't think so either.
Just for the future if you need it.
