### ISSUE TITLE
Lights programmed in rather than Appended

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#236]
**Is your feature request related to a problem? Please describe.**
I've had this idea for some time, to remove the lights in the humanoid_library.blend file, to then replace it with code that adds the lights.

**Describe the solution you'd like**
Removal of lights in humanoid_library.blend will not really reduce it's size much but it will keep the blend file for just meshes and armatures.

**Describe alternatives you've considered**
Removing the lighting option has been considered but it is a nice option to have this feature still

**Comment by Noizirom** [comment]
I think that the lights should be done via python, but I also think we
might need the lights tweaked to better mimic a 3 point lighting system.
I've been looking for an article I saw on setting up lights for still
renders to show what I mean.

**Comment by Noizirom** [comment]
All you would need to copy from the current setup is the settings and the
matrix_world. (Because it contains all the info you need to place them.
i.e. location, rotation, scale, etc...)

**Comment by animate1978** [comment]
Yeah I've been playing with code inside Blender itself this time, the rotation I can't seem to nail and the code is um....basic at best lol

I've also looked at the 3 point lighting add code that comes with Blender so may borrow from there too

**Comment by ldo** [comment]
If you are looking for an article on various kinds of portrait lighting, there is one saved at archive.org [here](https://web.archive.org/web/20140606102536/http://www.professionalphotography101.com/portrait_lighting/lighting_names.html).

**Comment by Noizirom** [comment]
@Ido thanks. What I  was looking for had different color lights.  Like one
yellowish, the back one blueish. Something like that.
@animate1978 if you copy the matrix_world of the original lights and make
the python lights matrix_world set to the original copy, then the locations
and rotations should take care of themselves. Just add the light to the
origin (0,0,0)

**Comment by ido** [comment]
@Noizirom i think you meant @ldo (Lawrence) not @ido (me).
