### ISSUE TITLE
Some places display parameter names instead of a string?

### ISSUE THREAD

**Issue by millionart** [animate1978/MB-Lab#24]
I have forked a copy to make a localized version and made some progress.

Most UI can be translated directly, but some places display parameter names instead of a string, which is not conducive to further thorough translation.

I want to ask if the next version can handle these places?

**Comment by telnetr4** [comment]
@millionart 
Im not sure I fully understand what you mean. Can you point to a specific place this happens?

**Comment by millionart** [comment]
My current method is to directly translate the strings in the source file. But some of the parameters that need to be adjusted, such as the following places:

![-1](https://user-images.githubusercontent.com/7535532/51724666-5f273180-2099-11e9-8ffc-9e70da782628.png)
![-2](https://user-images.githubusercontent.com/7535532/51724667-5fbfc800-2099-11e9-81e1-1dadf91c75b9.png)
![-3](https://user-images.githubusercontent.com/7535532/51724664-5e8e9b00-2099-11e9-9b40-de80e1509656.png)
![-4](https://user-images.githubusercontent.com/7535532/51724665-5f273180-2099-11e9-8cba-cd8a8f8cbb42.png)

These parts either cannot find a string, or directly translating a string may affect the data structure. I want to be able to string parameter names at least as well as the characters_config.json file.

In the end, I hope to support multiple languages, such as the bender's mo file.

**Comment by NumesSanguis** [comment]
It would also be nice to change the order of what to edit (such as Chest) to be in semantic order (top-to-bottom), such as Head --> Forehead --> Eyes --> Nose --> etc, instead of reversed alphabetic order column-wise.

**Comment by telnetr4** [comment]
Ah, ok.

I believe all of those parameter names are defined through the JSON files found in the data folder. Eventually these will most likely follow a module system (see [here](https://github.com/animate1978/MB-Lab/issues/14) for more details/vague notions).

A translation folder for modules might be necessary. I'm currently working on getting the basic module system working, but I'll keep this in mind.

**Comment by mklemarczyk** [comment]
I can dig into it on this week. Follow-up update (from me) expected on November 11th.
