### ISSUE TITLE
Hello, version 1.7.5 does not work for Blender 2.80

### ISSUE THREAD

**Issue by LarisaIvanovna** [animate1978/MB-Lab#242]
![0](https://user-images.githubusercontent.com/61454272/75233815-86838d00-57ca-11ea-9859-c204aceb17fa.png)
![Screenshot_6](https://user-images.githubusercontent.com/61454272/75233777-7370bd00-57ca-11ea-8729-b38863f615b6.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Logs**
`To format it correctly, logs should go in between these:`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.

**Comment by Noizirom** [comment]
I'm not sure, but I  do believe version 1.7.6 is for blender 2.80.

**Comment by LarisaIvanovna** [comment]
I'm sorry.
accidentally attached a screenshot with your answer.
thanks)

**Comment by LarisaIvanovna** [comment]
It does not work,I tried all versions of the addon.Very sorry((

**Comment by Noizirom** [comment]
You might need to try blender 2.81. I'm real not sure what the solution is
but the problem appears to be it cannot find something. I did not work on
that particular part of the code. I do apologize.

**Comment by LarisaIvanovna** [comment]
Thank you very much!
Yes, now in this case I just use blender 2.82.
Everything works there!)

**Comment by Noizirom** [comment]
Ok. I will try to see if we have archives somewhere. I'd think that there
would be a way on github. I'm still learning git. I'm sorry I couldn't be
of more help. Animate1978 will be away, I believe,  for a week or two
taking care of personal matters.

**Comment by Noizirom** [comment]
Sorry I've been looking for this. I've found it. A link to 1.7.6

https://github.com/animate1978/MB-Lab/releases/tag/1_7_6

**Comment by LarisaIvanovna** [comment]
Thank you very much!I will try)27.02.2020, 07:04, "Noizirom" <notifications@github.com>:Sorry I've been looking for this. I've found it. A link to 1.7.6

https://github.com/animate1978/MB-Lab/releases/tag/1_7_6

**Comment by Noizirom** [comment]
I'm glad I  could help. And for the future I now know where these are
stored.

**Comment by LarisaIvanovna** [comment]
I wish you success!Do you have an instagram profile?27.02.2020, 10:58, "Noizirom" <notifications@github.com>:I'm glad I  could help. And for the future I now know where these are
stored.

**Comment by Noizirom** [comment]
Thank you. No I do not unfortunately.

**Comment by animate1978** [comment]
So here is the situation.

The binary files in all versions EXCEPT version 1.7.7 have been purged, the repo got too big. If you download an old version you will get this error because the files don't exist so MB-Lab ceases to function.

Right now I am finalizing details on version 1.7.6 on the official website which will be published shortly, hopefully this will help.

I am hesitant about uploading older versions though because I believe 1.7.6 supports Blender 2.80. Otherwise if we keep going backwards in support or help it becomes harder to maintain, that's a lot of fragmentation.

**Comment by animate1978** [comment]
https://mblab.dev/download/mb-lab-1-7-6/

**Comment by LarisaIvanovna** [comment]
Thank you very much.I work with the Blender version 2.82,everything works there.Thank you for your work.04.03.2020, 18:09, "animate1978" <notifications@github.com>:Closed #242.
