### ISSUE TITLE
Face Rig creation process failed

### ISSUE THREAD

**Issue by xscs709560271** [animate1978/MB-Lab#243]
**Describe the bug**
It seems like just me have a chance to meet this error.

**To Reproduce**
1. Downloaded the 'MB-Lab-1_7_7.zip' from github.
2. Install add-on in Blender 2.82 and 2.81 both.  
3. I  create a new sence and use MB-Lab 'create a character'
4. And I finalized my character.
5. When I clicked 'Create Face Rig' button, it will shown an error called "Face Rig creation process failed"

**Screenshots**
![](https://s2.ax1x.com/2020/03/04/3IELSU.png)

**Additional context**
I don't figure out why I met this. I have tried on blender 2.80/2.81/2.82 and it still shows the same error.

**Logs**
```
"Face Rig creation process failed"
```

**Comment by animate1978** [comment]
Hmm this one is new, I will have to look into this one.

**Comment by TetoTheSquirrelFox** [comment]
@animate1978 :
class CreateFaceRig in __init__.py, method execute
The error exists only here.
It's when facerig.setup_face_rig(obj) return None for a reason.

@xscs709560271 : When you have this error, your model is selected ?

**Comment by xscs709560271** [comment]
> Hmm this one is new, I will have to look into this one.
> 
> Will it be possible for you to send me a blend file? I cannot seem to reproduce this

Thanks for replying. I have uploaded it here. But I am not sure whether it will show again.

blender project:
[mb-lab-demo.zip](https://github.com/animate1978/MB-Lab/files/4290514/mb-lab-demo.zip)
finalized and backup:
[demo.zip](https://github.com/animate1978/MB-Lab/files/4290530/demo.zip)

**Comment by xscs709560271** [comment]
> @animate1978 :
> class CreateFaceRig in **init**.py, method execute
> The error exists only here.
> It's when facerig.setup_face_rig(obj) return None for a reason.
> 
> @xscs709560271 : When you have this error, your model is selected ?

Thanks for replying. Yes. I have selected the model. I will have more tests.

**Comment by abhayks** [comment]
Hi,
I'm also facing the same issue . MB Lab version 1.7.7



Read prefs: C:\Users\abhay\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
Loading MHX2 importer-runtime v 0.30
build loaded
MHX2 armature loaded
MHX2 successfully (re)loaded
mb_lab updater verbose is enabled
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_install_popup'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_install_popup'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_check_now'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_check_now'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_update_now'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_update_now'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_update_target'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_update_target'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_install_manually'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_install_manually'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_updated_successful'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_updated_successful'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_restore_backup'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_restore_backup'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_ignore'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_ignore'>
cls BA: <class 'MB-Lab.addon_updater_ops.addon_updater_end_background'>
cls: <class 'MB-Lab.addon_updater_ops.addon_updater_end_background'>
mb_lab Updater: Read in json settings from file
Info: Deleted 1 object(s)

C:\Users\abhay\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MB-Lab\data\face_rig\face_rig_lib.blend not found. Might need to reinstall ManuelBastioniLab
Error: Face Rig creation process failed

**Comment by animate1978** [comment]
Somehow this file was NOT in this version? (facepalm)...

I am so sorry guys I will have this corrected asap

**Comment by abhayks** [comment]
I have manually downloaded and copied the files 
face_rig_lib.blend
and 
facial_rig.blend
to 
C:\Users\abhay\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MB-Lab\data\face_rig\

Works now :) 
Thanks

**Comment by animate1978** [comment]
OK hopefully I will be more mindful of data when releasing new versions so that things like this can stop happening to you guys.
