### ISSUE TITLE
Render time is Huge

### ISSUE THREAD

**Issue by abhayks** [animate1978/MB-Lab#245]
Hi,
Just created a new character by selecting only one option
" Use EVEE" 
Nothing else selected, no IK, no Lights. 
Render time in EVEE is 6.52 seconds ( on average). 

Tried importing a character from Makehuman 
Again using EVEE, render time is 0.27 seconds ( avg). 

As much as I like mbLab, this huge render time means that my full project render will take days. 
Any way we can reduce render time ?

**Comment by Anyeos** [comment]
Are you using the shaded view?
You can reduce the amount of polygons disabling the modifiers too. Disable te displacement and so.

First, use a wireframe view to achieve max speed. Next, choose the options that I said.

The shaders normally are some heavy. On my computer it took more or less time depending of the complexity of the shader.
The shader is GPU intensive so if it is complex you likely will have greater render times.

When you finish your character creation you can edit the material and look what is hapenning. You can modify it too or use another combination of nodes if you want. Handle it by yourself there are no more choices.

**Comment by mklemarczyk** [comment]
Please specify the hardware and render configuration.

**Comment by animate1978** [comment]
Not to be harsh but but I have projects that take even longer to render, it is also not uncommon for projects to render taking even longer than a few days. I realize that people want instant results with EEVEE but the goal of MB-Lab is realism, even if that render time is increased, 6+ seconds is not exactly a long time to render.

The shader for MB-Lab skin is quite complex and the MakeHuman models simply do not have the level of realism that MB-Lab is trying to obtain.

Again if you look at render times for feature films where renders take days and weeks 6 seconds on EEVEE is not so bad.

**Comment by thelabcat** [comment]
"6 SECONDS? Can we trade?"

**Comment by thelabcat** [comment]
Maybe try baking some of the shader elements to images, and particularly setting subsurface scattering to just diffuse.￼
