### ISSUE TITLE
Just an idea, about tabs

### ISSUE THREAD

**Issue by TetoTheSquirrelFox** [animate1978/MB-Lab#249]
I was working on a tool tonight, and I thought about something during tests and debugging.

For the moment there are 2 tabs :
- the main one, named MB-Lab and created by Manuel Bastioni, for an addon developed in an end user point of view. Aka you have a model, you change its shape, and then you finalize it, and things like facial expressions or textures/materials are added, for animation, model in game and so on.
- I added a second tab, with a bizarre name that @animate1978 doesn't like ^^ , dedicated to creation or edition of things that an end user doesn't care.

While I was testing things this evening, I was thinking that tools that are available since the beginning (below) don't really fit here, because there tools used AFTER finalization, and dialogs to load a finalized model are also there. The tools disappear when shaping the model, come back after finalization, it's not obvious or very user friendly, imho.
![image](https://user-images.githubusercontent.com/59537161/76261372-21b04400-625a-11ea-9df0-0cd021ea0c78.png)
The problem here is that part will grow a lot if the addon expends as intended. Hair technics, clothes, objects or new technics to use a model after finalization.

So I was thinking that maybe it would be interesting to have in fact 3 tabs : 
- MB-Dev. Named MB-Crea before. The tab could be masked by an option in general properties (if it's possible). Here we would find all tools for creating "all behind the scene" stuff like morphs, base model and so on.
- MB-Lab. All tools to shape a model, from an end-user point of view.
- MB-Final (or other name). There you do what you want when the model is frozen (add hair, clothes, ...)

I think that it would be interesting to do that because we would have a clear separation between tools BEFORE finalization and AFTER. And a good separation between the "basic" user and the creator that wants to make a model from A to Z.

Feel free to say that it's stupid, I won't be mad. ^^ Just a thought I had tonight.

**Comment by animate1978** [comment]
Actually that does sound like a good idea.

I think it would have to remain 3 tabs at most, I think people will still complain because the N panel tend to get crowded with addons. However in this instance MB-Lab is BIG, in size and complexity so differentiating between the tasks would, I think, overshadow that it would take up 3 tab spaces.

**Comment by TetoTheSquirrelFox** [comment]
If it's possible, we could have the MB-Lab disappear when the user finalizes his character, or when he loads one, and MB-Final shows up... then disappears when user starts a new session. MB-Dev would be just an option in the properties. So just one tab in general (MB-Llab/MB-Final) and a 2nd one in option.

**Comment by animate1978** [comment]
So I have an idea... instead of new tabs which I think would upset users... what about doing similar to the "View" Tab...
![new_gui_example](https://user-images.githubusercontent.com/479115/76759598-019ceb00-675a-11ea-87d7-b70344275b0d.png)

One for MB-Lab, another for 'MB-Dev/Gen' (MB-Crea) and we can split up the Creation tools and After Creation tools this way too maybe? I don't know I have to look through some files first.

**Comment by TetoTheSquirrelFox** [comment]
Yep, for example, that looks very good actually.
And the best of the best would be to have many tools under this form :
![image](https://user-images.githubusercontent.com/59537161/76781087-726df280-67ae-11ea-8f74-744926826566.png)
But it's a LOT of work I think... ^^

**Comment by animate1978** [comment]
So I managed to get some code working for this idea...

![new_gui_shot_01](https://user-images.githubusercontent.com/479115/76855802-e694ae80-681f-11ea-8c33-411cdd72296d.png)
![new_gui_shot_03](https://user-images.githubusercontent.com/479115/76855808-e98f9f00-681f-11ea-9ffb-57d9679ffeea.png)

`
class VIEW3D_PT_tools_MBCrea(bpy.types.Panel):
    bl_label = "MB-Crea {0}.{1}.{2}".format(bl_info["version"][0], bl_info["version"][1], bl_info["version"][2])
    bl_idname = "OBJECT_PT_characters02"
    bl_space_type = 'VIEW_3D'
    bl_region_type = 'UI'
    bl_context = 'objectmode'
    bl_category = "MB-Lab"
    bl_options = {'DEFAULT_CLOSED'}

    @classmethod`

I changed the bl_category to MB-Lab and then added the bl_options, which then closes that window on startup.

**Comment by TetoTheSquirrelFox** [comment]
Damn cool ! ^^
And so easy to do. Just one line ! ^^
