### ISSUE TITLE
installing add on problem

### ISSUE THREAD

**Issue by hadschiandrova** [animate1978/MB-Lab#26]
Somehow I get this message and cannot install the add on.. any suggestions?

![blender user preferences 06 01 2019 23_34_39](https://user-images.githubusercontent.com/46428646/50742524-aa71c100-120c-11e9-90d9-ee586312c5b4.png)

**Comment by NumesSanguis** [comment]
Blender 2.79b or 2.80?

**Comment by hadschiandrova** [comment]
2.79
would it still work somehow?

**Comment by animate1978** [comment]
No. MB-Lab 1.7.0 is for Blender 2.80 Beta, you want MB-Lab 1.6.5 which is on the releases page
