### ISSUE TITLE
Utilities > Choose a proxy reference > Import template fails

### ISSUE THREAD

**Issue by billhails** [animate1978/MB-Lab#263]
**Describe the bug**
See the Subject

**To Reproduce**
1. Open a new blendfile.
2. Open MBLab tab
3. Open Utilities
4. Choose a proxy reference
5. Import template
5. See error

**To Fix**
in `__init__.py` change `algorithms.get_blendlibrary_path()` to `file_ops.get_blendlibrary_path()`

There's only one occurrence.

**Comment by TetoTheSquirrelFox** [comment]
Thanks for the bug.
Actually, the bug is fixed in dev version (just checked that).
Short story, the method was initially in algorithms but was relocated in file_ops as all methods that are related to file.

**Comment by billhails** [comment]
Ok, glad it's fixed, thanks!
