### ISSUE TITLE
Phenotypes did not Fully Install

### ISSUE THREAD

**Issue by DrIgnatiusCole** [animate1978/MB-Lab#268]
**Describe the bug**
Installing MB-Lab 1.7.7 resulted in only 4 phenotype meshes being installed.

**To Reproduce**
1. Download MB-Lab from site
2. Install in Blender 2.83 on Ubuntu 20.04 LTS via zip file in downloads
3. Installer only partially installed phenotypes (and maybe not everything else I am not sure yet).

**Expected behavior**
The full complement of phenotypes should have been installed. The installer only installed the "A's"; aboriginal, african, afroasian, afromediterranean.

**Screenshots**
![Characters Library missing phneotypes](https://user-images.githubusercontent.com/65957201/82901118-64c6ad00-9f55-11ea-9063-2662087335d7.png)

**Additional context**
It appears the .json files are included in the download, but not installing in the installer. The "hu_m_anthropometry" is populated. I have not tried re-downloading. 

**Logs**

**Comment by DrIgnatiusCole** [comment]
Correction: There is Phenotypes folder which is in the data folder of the installation, but they are not visible in Blender/MB-Lab. I'm still trying to find a way of getting them into Blender/MB-Lab.

**Comment by TetoTheSquirrelFox** [comment]
OK. I think that I understand you problem. Tell me if I'm wrong. You see 4 phenotypes, but in the folder, there are many more. It's normal, as the phenotypes can't be used for every base model. Caucasian has many more than African for example, yes.

**Comment by animate1978** [comment]
Yes the phenotypes are built for each "race" as it were, so the Afro types are different than the Caucasian types.

Over time these phenotypes will be expanded and created. Remember than MB-Lab is a very big project in itself with different people working on different parts, I myself was unable to work on MB-Lab for a couple of months due to personal obligations.

**Comment by DrIgnatiusCole** [comment]
Nope - I think the problem was pilot error...ie me. You are supposed to choose the type of character at the top, which was not obvious to me. Whatever my problem was at the time it is resolved.

**Comment by animate1978** [comment]
Cool I will close this issue then
