### ISSUE TITLE
Anime character imported to mixamo or unreal 4 has no color

### ISSUE THREAD

**Issue by coconutteamlive** [animate1978/MB-Lab#271]
Hi,

I'm using blender version 2.8.30 and have installed the MB_LAB add on.
I tried to create a basic Anime character (built in) one from MB_LAB, I then exported the model to a *.fbx, the UV image to a *.png and zipped to a zip file. I then upload that zip file to mixamo, but the uploaded character has *no* color.

I also tried imported the *.fbx to unreal 4, and got the same result, the imported character has no color.

I tried other options like *.obj and upload to mixamo but got similar result.

I've spent many hours on this but still no luck on this.

Anyone has any idea? Any help would be appreciated. (I've done some researches on similar topics but haven't yet found a solution.)

Thanks!

**Comment by TetoTheSquirrelFox** [comment]
It may be not a good answer, but the anime character was actually not finished when Manuel Bastioni (the author) left his project. So it may be normal. And nobody continued after him.

**Comment by animate1978** [comment]
Currently I do not a system powerful enough to build Unreal, I have been using Ubuntu 16.04 and my hardware is not up to par.

I do plan on buying a new system here very soon so I can continue to develop, and Unreal 4 will be installed on that system when I do acquire it.

MB-Lab to Unreal export has always been a bit troublesome in the past, usually involving custom shader work in Unreal 4 but again I have no real way to test this at this time. I do plan on doing so in the future as Unreal 4 is a very common used engine.
