### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#276]
**Describe the bug**
Testing out new MB-Dev framework

**Logs**
`Error: Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.82/scripts/addons/MB-Lab/__init__.py", line 4891, in execute
    name = splitted[0] + "_" + splitted[1] + "_polygs.json"
IndexError: list index out of range

location: <unknown location>:-1
`

**Comment by TetoTheSquirrelFox** [comment]
The error means that splitted is empty or None.
Here it's because the variable "key" is none (-1).
So that means I have to had a security check.
I'm on it.
