### ISSUE TITLE
New Realistic Base Mesh & Shader

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [animate1978/MB-Lab#277]
# Preface
A Big issue with MB-Lab is Licensing Concerns of the base mesh that manuel bastioni has created, which splits the license into two separate parts, GPL for the Code and AGPL for assets created, what intend to do is to help bridge this division of licenses and bring forth more realistic characters as well as take advantage of Teto's New Features. I intended to open this up as i started working on it but i didn't want to make an issue of something that wasn't remotely  done so I will try and Update things as time goes on. 

# Base Mesh
For the New Base mesh i sought out free base meshes for use in zbrush and ultimately decided to use Javier Zuccarino [free base meshes](https://gumroad.com/zuka) he published in 2017 on gumroad. Unfortunately only the female body was fully sculpted while he had both male and female heads available. So the solution i found was to sculpt the male body from the female body using multires. The base mesh has about 20K Faces which is slightly more than the original but should have a minimal impact on performance. Both the male and female base meshes have the same faces but they are sculpted to create things like a less arched back, less wide hips and pectoral muscle instead of breasts. The results are far from perfect but that is the reason i chose to use multires and allow changes to be reverted at any time. And things like teeth in the mouth are missing. I feel like facial features are quite extreme. 

## <b>Male (Matcap)</b>
<img src="https://user-images.githubusercontent.com/45346421/86516867-25ec0880-bdd9-11ea-80b0-aa00e24f513a.jpg" width=300  align=center></img>
## <b>Female (Matcap)</b>
<img src="https://user-images.githubusercontent.com/45346421/86516929-a579d780-bdd9-11ea-9747-850bdaf4b987.jpg" width=300 align=center></img>

# Shader
The Shader is culmination of more than 2 months of work between me and SopitaFria on MB-Lab's Discord. The Intent was to create a Procedural Skin Shader with lots of Customizability much more than the original Base Mesh's Shader, Most Focus of Development went into a good face shader with the rest of the shaders being based off the one decided for the face mostly due to the fact we wanted a good face shader before moving onto making amazing shaders for the arms, legs and torso, however they are not often updated to have remotely the same amount of features. This Also is the same for Eye Shader which is entirely procedural with no masks but lacks necessary details. We haven't implemented a shader  for the Mouth yet however there is existing Uv's and Material for it. But Keep in mind it has no teeth and leaves a lot to be desired
<img src="https://user-images.githubusercontent.com/45346421/86517289-a4967500-bddc-11ea-9353-fc7f68b186bd.jpg" width=300 align=center>
<img src="https://user-images.githubusercontent.com/45346421/86517378-53d34c00-bddd-11ea-87c5-0dd7ce54a82b.png" width=300 align=center>

# Download
Note: Do not use Optix for Cycles because we use Ambient Occlusion for realism
Because the Shader is Procedural with some exceptions, the base meshes are in total less than 50mb:
[Google Drive](https://drive.google.com/file/d/14SY6pGT1B2SY0-i6YfXPQVpnoruxkdct/view?usp=sharing)

**Comment by TetoTheSquirrelFox** [comment]
Quick answer about something I read somewhere a while ago (and I didn't think to save the link, sorry).
It's related to this topic but not about your work, which is great.

I was of the guys, years ago, who was thinking that the MakeHuman model was too low poly to be really useful for something else that game character (for a game where photorealism is not important). I wanted more vertices/faces. Since then, MB-Lab was released with slightly more polygons. But I was thinking that more is better.

But, I read, somewhere, few months before I started to help here, that in fact models must not have too much polygons, for a good reason. Their behavior in animation. Models don't react well, when you have to deform faces in order to animate them. Shrink, expand or deform faces work better when there is space between vertices.

My remark is just about that : High poly is good but not so much.

I've just watched the new model : it's good, but I think that we can't go further (about faces number).

**Comment by Hopefullyidontgetbanned** [comment]
Updated to Include A Mouth Material and cleaned up the Female Model, Material Wise

**Comment by Hopefullyidontgetbanned** [comment]
@TetoTheSquirrelFox  the Number of polygons increased from the original mb-lab base is marginal so it shouldn't matter

**Comment by animate1978** [comment]
I have been following your progress and it does look good. These models, as long as they are licensed properly should be good candidates.

Right now I am testing a toon girl model for the process of adding a new character to MB-Lab, once that gets hammered down well and released this could be the next addition.

The reason for this is not to exclude your work but to go through a testing and development phase, I have been working on the toon girl model for some time, is properly licensed and am halfway finished with development.

The development of this is half Blender side and the other half MB-Lab/Dev side. there is a lot to cover on both to make the models compliant with MB-Lab's code and workflow.

The toon girl development is simple in comparison to development of realistic human models, even though the mesh is well done (at least from what I have seen), the shader work is kind of weird (more on that at a later time)... in all things would need to be worked on for both toon and realistic models.

This is not to say that your work in this has been discounted, it just might take longer for it to be added simply because users of MB-Lab expect things like morphs and expressions, things that are not present in both this and the toon model. Much needs to be done before anything is released to the public as "official" as it may.

**Comment by Hopefullyidontgetbanned** [comment]
i'm fine if it isn't the biggest priority but i would like it to be tackled after the toon model. i'm not perfect with sculpting or material creation and i have laid out what is wrong or missing with various issues which i would like to see fix before anything is done to integrate it, I was planning to integrate to rigify's meta human rig due to the fact it is easier to pose and and has issues in things like game engines/external tools and is more universal

**Comment by Hopefullyidontgetbanned** [comment]
Updated Lip Color and Color Variation and a marginally improved torso shader, though it needs to be overhauled to have the quality of the face shader just like the arms and legs as well, the eyes should also be tackled at one point or another

**Comment by Hopefullyidontgetbanned** [comment]
[Updated ](https://drive.google.com/file/d/14SY6pGT1B2SY0-i6YfXPQVpnoruxkdct/view?usp=sharing)Sculpt and Shader, you can transfer the updated shader to the old sculpt if you want, i just wanted to have a more androgynous base mesh so that more gendered features would be handled through morphs
![multires](https://user-images.githubusercontent.com/45346421/86943248-0ddaf880-c0fb-11ea-924b-c5fe7174dd63.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
[Updated](https://drive.google.com/file/d/14SY6pGT1B2SY0-i6YfXPQVpnoruxkdct/view?usp=sharing)
Updated Skin Shader, Overhauled Eye shader, and improved sculpt.
![Render1](https://user-images.githubusercontent.com/45346421/87114948-cc476c00-c226-11ea-88e8-4e8081df5ffd.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
[Updated](https://drive.google.com/file/d/14SY6pGT1B2SY0-i6YfXPQVpnoruxkdct/view?usp=sharing)
Shader Improvements and clean up

**Comment by animate1978** [comment]
OK so it may be an issue with my system but the shaders do not compile well for EEVEE, at least not on my end.

![base mesh sculpt(1)](https://user-images.githubusercontent.com/479115/87251354-b73e2900-c430-11ea-9dcf-7d56842f95ca.png)

They work fine for Cycles though.

![base mesh sculpt(1)_cycles](https://user-images.githubusercontent.com/479115/87251371-d937ab80-c430-11ea-8387-7a471dc0f60a.png)

Must remember that people expect EEVEE now that it has become a standard for Blender 2.80+...

**Comment by Hopefullyidontgetbanned** [comment]
from my experience on my machine it works with eevee it's just a bug that you sort of have to figure out

**Comment by Hopefullyidontgetbanned** [comment]
[Updated](https://drive.google.com/file/d/14SY6pGT1B2SY0-i6YfXPQVpnoruxkdct/view?usp=sharing) Base Mesh, Would like if someone could massive fix the anatomy of this mesh as it's a biggest issue i have with it so far, as for the shader i did some improvements across the board and tried experimenting with Vertex Colors for Dirty AO
But i cannot stress enough that i'd like to see fixes to the anatomy as it bothers me greatly

**Comment by Hopefullyidontgetbanned** [comment]
I also tried to make a [Muscular Base Mesh](https://drive.google.com/file/d/1kuMBOVoxBeWB1liKR_uV-cBXw9AThzGI/view?usp=sharing)
However the results anatomy wise still leaves a lot to be desired, it's imperative we find a solution for the male base mesh's anatomy
![mb-lab](https://user-images.githubusercontent.com/45346421/87885231-2d123980-c9c9-11ea-8da2-75e774ab3e7a.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
![MB-lab3](https://user-images.githubusercontent.com/45346421/87891317-60b38a80-c9ee-11ea-8e94-b1be1ec29efc.jpg)
[here](https://drive.google.com/file/d/1hhScfOBQIcqaFjqhkU6iQteDm94mrGMB/view?usp=sharing) is another attempt for better male anatomy

**Comment by Hopefullyidontgetbanned** [comment]
so i would probabbly say this is my last revision until the times come for a new shader and base mesh to be actually implemented. i hope this has been useful so far
https://drive.google.com/file/d/14SY6pGT1B2SY0-i6YfXPQVpnoruxkdct/view?usp=sharing
![basemesh_female_workbench](https://user-images.githubusercontent.com/45346421/88741651-12d90980-d0f5-11ea-8040-12ef27e8410d.jpg)
![basemesh_male_workbench](https://user-images.githubusercontent.com/45346421/88741653-14a2cd00-d0f5-11ea-8d88-63ca75eda18c.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
![Mouth](https://user-images.githubusercontent.com/45346421/89137575-68465980-d4ed-11ea-9bbf-b0cc98a22a73.png)
New Mouth Model you can try and replace base mesh's mouth, i just redid the uv's and materials from the current base mesh and shoved into the existing mouth so the results are not that great but it's okay for now [Download](https://drive.google.com/file/d/1on-_s_N7Mlg2Z_dFNgRbFhLicGz0gsu6/view?usp=sharing)

**Comment by Hopefullyidontgetbanned** [comment]
# Update - (August 15th)
## New Approach
So this approach is actually the same as the current mb-lab shader, however it is intended to be more dynamic and to use less maps.
![Substance8AO](https://user-images.githubusercontent.com/45346421/90326352-3c3ec580-df3c-11ea-9dbe-d8b49f03ff2c.png)
[Download Substance Painter File](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)
The Approach is to have 2 Color Maps for Light and Dark Skinned  Characters and to interpolate intermediary skin tones
The Image Maps were painted in Substance Painter using a mix of texture maps and smart materials, and AO from High Poly Displacement meshes, this approach is compatible with both Optix and CUDA
![Substance10](https://user-images.githubusercontent.com/45346421/90326341-19acac80-df3c-11ea-828e-d1792274f446.png)
[Download Substance Painter File](https://archive.org/download/base-mesh-mb-lab/skin_paint_dark.spp)
[Download Final Blender File](https://archive.org/download/base-mesh-mb-lab/BaseMeshSubstance.blend)
The Shader is basic in terms of customizability but that is to be added as time goes on
## Updated 
![femalesculpt3](https://user-images.githubusercontent.com/45346421/90326473-8c6a5780-df3d-11ea-9eb4-801236b0efc4.jpg)
[Download Sculpt Blender File](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20sculpt.blend)
Improved Female Sculpt to be more feminine, the eyelids aren't perfect though

**Comment by Hopefullyidontgetbanned** [comment]
# Update - (August 28)
## Skin Shader Updates
![DarkerSkin](https://user-images.githubusercontent.com/45346421/91611908-20222780-e931-11ea-9c43-51e680e824aa.png)
[Download Substance Painter File](https://archive.org/download/base-mesh-mb-lab/skin_paint_dark.spp)
[Download Final Blender File (Exported Textures)](https://archive.org/download/base-mesh-mb-lab/BaseMeshSubstancePacked.blend)
![LightSkin](https://user-images.githubusercontent.com/45346421/91612033-624b6900-e931-11ea-8248-c2ef1957fbfe.png)
[Download Substance Painter File](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)
## Sculpt
Reduced Shoulder Muscles to be more congruent with the rest of the body type
[Download Sculpt](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20sculpt.blend)
![sculpt1](https://user-images.githubusercontent.com/45346421/91612615-9c693a80-e932-11ea-99a2-927797fb81af.png)
## Demonstration
![Alexander_HairPractice_8_27_2020_front](https://user-images.githubusercontent.com/45346421/91612460-544a1800-e932-11ea-9bdc-12b67a0ba291.png)

**Comment by HarshEcka** [comment]
Wonderful work....I myself was trying to create high res albedo maps in texture paint....I have come wonderful cg artist named chamberasu in sketchfab....He shares his project free..He has made shaders for cloths as well as skin and shares them in patreon...Link
https://www.patreon.com/chambersu

**Comment by HarshEcka** [comment]
Also can you explore luxcore render engine for skin as I feel it creates more realistic look compared to Cycles..

**Comment by HarshEcka** [comment]
![Tex_Premium 1033](https://user-images.githubusercontent.com/69085843/91628184-fde4e400-e9da-11ea-9f17-3373cd1028d2.png)
New albedo map in texture paint..

**Comment by HarshEcka** [comment]
![Luxcore_1](https://user-images.githubusercontent.com/69085843/91628224-4dc3ab00-e9db-11ea-988a-20781a543e9d.png)
Lux Core skin shading

**Comment by HarshEcka** [comment]
I am thinking that we should sculpt the models with multires and add details such as pores and wrinkles and bake the diffuse map in exr format.. along with normals and rest of the maps will be procedural.. No need for hair r beard as same can be achieved with particle systems..Or we can share two version of maps one high res and low res and give the users choice that what they want to use in their projects..

**Comment by HarshEcka** [comment]
https://blenderartists.org/t/fully-procedural-skin-shader/1226438
'
This is an amazing procedural texture.. Sadly the nodes are not readable..

**Comment by HarshEcka** [comment]
https://blenderartists.org/t/human-progress/1143224

This is also amazing work by Chris Jones... All the textures were hand painted..No photo scanning

**Comment by Hopefullyidontgetbanned** [comment]
the model i used was made by Javier Zuccarino and it seems to fit the needs of this project although i had to sculpt the male version a lot as for  the textures, i do not know how Chris Jones painted his textures but i am quite happy with mine so far, i've considered using multires to sculpt high poly versions but i feel currently like it's unnecessary and doesn't quite fit with my workflow using substance painter to make bump/displacement maps

**Comment by HarshEcka** [comment]
Ok. Thanks for the reply.. I will try to create shaders for luxcore. Have you considered looking at the Chambersu work.. he has used MBlab models as base mesh. He has shared his project blend files in is patreon page.. Without being patreon we can access his work. His cloths work is awesome. His skecthfab pages for final results are 
https://sketchfab.com/3d-models/head-ring-jewly-hair-pin-retopo-and-hairstyle-09294cb14a404d77ad3db9ff6ab49179
and his project files are in
https://www.patreon.com/chambersu

**Comment by Hopefullyidontgetbanned** [comment]
@HarshEcka it's nice to see someone use mb-lab in production but  it is obvious they are going for a stylized approach which conflicts with my goals. if you have the skills to texture in substance painter or create shaders be my guest. i've provided my assets in this thread

**Comment by HarshEcka** [comment]
i Have tweaked the original shader along-with new albedo map... Give your reviews regarding the skin.. 
![4](https://user-images.githubusercontent.com/69085843/91650835-4f0bdb00-eaa2-11ea-9db4-58974bfa73dd.png)

This is the old shader with albedo map
![Tex_Premium 1032](https://user-images.githubusercontent.com/69085843/91650838-54692580-eaa2-11ea-97e0-1517ee784aec.png)

**Comment by Hopefullyidontgetbanned** [comment]
the results look very vibrant but not sure how it would apply to my shader
https://archive.org/download/base-mesh-mb-lab/BaseMeshSubstancePacked.blend
try this mostly because it's a complete overhaul of everything regarding shaders and textures that comes with the new base mesh

**Comment by HarshEcka** [comment]
Ok try to acheive the same effect with your base mesh.

**Comment by Hopefullyidontgetbanned** [comment]
## Update
[Work In Progress Rig](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized.blend)
![basemesh_substance6Pose](https://user-images.githubusercontent.com/45346421/91684050-266bfb80-eb0b-11ea-8e45-93854b023000.jpg)

**Comment by Hopefullyidontgetbanned** [comment]
## Update
[Work In Progress Rig/Updated Female Sculpt](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_9_18_2020%20Packed.blend)
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)
[Dark Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_dark.spp)
Massive Jump in Realism through lighting and better skin and eye materials.
![substance35](https://user-images.githubusercontent.com/45346421/93657302-a38de080-f9e6-11ea-9b25-d6bff39681fa.jpg)
![substance36](https://user-images.githubusercontent.com/45346421/93657649-2d3ead80-f9e9-11ea-83c2-149462f70968.png)

**Comment by Hopefullyidontgetbanned** [comment]
## Update
[Work In Progress Rig/Updated Female Sculpt](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_10_02_2020%20Packed.blend)
![substance41_female_8](https://user-images.githubusercontent.com/45346421/94981819-24220600-04ea-11eb-9e5f-1c425a99a529.png)
Massive Improvements to female head mesh
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)
(Using only 1 skin tone as a base rather than 2 like what CharMorph does)

**Comment by Hopefullyidontgetbanned** [comment]
## Update
[Work In Progress Rig](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_10_11_2020%20Packed.blend)
![substance45_female-1](https://user-images.githubusercontent.com/45346421/95758247-0e84ad00-0c5d-11eb-9407-c7fe5e3812e4.png)
Massive Improvements to Skin Texture Quality
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)
(Using only 1 skin tone as a base rather than 2 like what CharMorph does)

**Comment by Hopefullyidontgetbanned** [comment]
## Update
[Work In Progress Rig](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_10_21_2020%20Packed.blend)
![substance57](https://user-images.githubusercontent.com/45346421/96798225-499d8380-13b5-11eb-8f18-5ec8e039db37.png)
Minor Improvements to Skin Texture Quality
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)

**Comment by Hopefullyidontgetbanned** [comment]
## Note
The New Eye was based on [this procedural one](https://gum.co/JTuvRL) with manual edits after Baking

**Comment by Hopefullyidontgetbanned** [comment]
## Update
Major Fixes to Oversights
[Work In Progress Rig](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_11_02_2020%20Packed.blend)
![substance64](https://user-images.githubusercontent.com/45346421/97939780-57012900-1d38-11eb-8eef-f34118ed8319.png)
Improvements to Skin Texture Quality
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)

**Comment by Hopefullyidontgetbanned** [comment]
## Update
Fixes to Oversights
[Work In Progress Rig](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_11_15_2020%20Packed.blend)
![Substance69](https://user-images.githubusercontent.com/45346421/99190418-55ae0400-271b-11eb-8948-ff596d273df2.png)
Improvements to Skin Texture Quality (Especially hands)
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)

**Comment by Hopefullyidontgetbanned** [comment]
## Update
Updated Textures
[Work In Progress Rig](https://archive.org/download/base-mesh-mb-lab/base%20mesh%20rig%20finalized%20Rev_12_01_2020%20Packed.blend)
![Substance79](https://user-images.githubusercontent.com/45346421/100792050-eb5dba80-33ce-11eb-8741-5abf1f3e4317.png)
Improvements to Skin Texture Quality (Especially hands)
[Light Skin Tone Substance Painter Project](https://archive.org/download/base-mesh-mb-lab/skin_paint_new.spp)

**Comment by animate1978** [comment]
Looking quite good there Hope! I will be downloading files of this

**Comment by cellis** [comment]
What is the license of these new base meshes?

**Comment by Hopefullyidontgetbanned** [comment]
> What is the license of these new base meshes?

Probably CC0 but I never finished it so it doesn't matter anyways, I'm spending my time on the vitruvian project for charmorph which should be done in a few months. Could close this issue but I think having support for custom characters is still important for MB-Lab.

**Comment by Hopefullyidontgetbanned** [comment]
Closing this as the future of MB-Lab has been sealed, Vitruvian is the proper realization of this project and will come to the next Charmorph version.
