### ISSUE TITLE
Creation Ops model file loading error

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#279]
**Describe the bug**
When attempting to load a model file into MB-Dev 

**To Reproduce**
Create the project
Create the config files
Load the model file

**Expected behavior**
To load the model file

**Logs**
`Error: Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.82/scripts/addons/MB-Lab/__init__.py", line 5620, in execute
    creation_tools_ops.load_blend_file()
  File "/home/farishta/.config/blender/2.82/scripts/addons/MB-Lab/creation_tools_ops.py", line 309, in load_blend_file
    with bpy.data.libraries.load(lib_filepath) as (data_from, data_to):
UnboundLocalError: local variable 'lib_filepath' referenced before assignment

location: <unknown location>:-1
`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.

**Comment by TetoTheSquirrelFox** [comment]
Have you put your model under /data/ ?
With its name as "your_project_name"_library.blend ?

For the bug it's not a bug, I just forgot to add a "return" if the file is not found.
Change the file and push it in the repository.

**Comment by animate1978** [comment]
The file is in /data

The file is named toon_female_library.blend

**Comment by TetoTheSquirrelFox** [comment]
Can you send me your config file please ?

**Comment by animate1978** [comment]
[toon_girl_config.zip](https://github.com/animate1978/MB-Lab/files/4874767/toon_girl_config.zip)

**Comment by TetoTheSquirrelFox** [comment]
OK. First, your config name should have the same name as the blend file aka :
xyz_library.blend
xyz_config.json
I take your blend and try to recreate your bug from your description, but for me something got wrong when you created the config file. Stay tuned.

**Comment by TetoTheSquirrelFox** [comment]
OK. So, how it goes :
I decided while coding all of this, to unify names in projects, to avoid gancy ones, and projects with different names for the same thing. And to be as simple as possible, I decided that the project name must be alphanumerical only, without characters like "_-è=" and so on.

So when I start with your names I already have a problem :
![image](https://user-images.githubusercontent.com/59537161/86530926-5311e700-bebd-11ea-9373-68a0c1f59a6f.png)
I named the project as your blend, and _female is cut.
So I named your blend toon_library.blend, so it could have after a male model as well.
![image](https://user-images.githubusercontent.com/59537161/86530962-a3894480-bebd-11ea-9c10-877148d8cee4.png)

(I update this comment each time I finished something, to let you do the same thing on your side)

**Comment by animate1978** [comment]
Hmm... so I managed to get past the "Load models file" !

So not so much a bug after all

**Comment by TetoTheSquirrelFox** [comment]
No and I see where your problem was : your name of the project is different of the name of you blend, and the name of your blend has a '_' (aside '_library').

So rename your config file 'toon_config' and your blend file 'toon_library' and that should be OK. I quited Blender, re-opened it, tried to load your project, and the model loaded.
