### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by maxrena** [animate1978/MB-Lab#28]
Here is what I encountered today.
https://imgur.com/a/j6MvLo2

**Comment by ldo** [comment]
As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.

I’m sure I speak for the maintainer of this repo, and for all other repo maintainers.

**Comment by animate1978** [comment]
Could you list the steps to get this error so I can see where the problem lies?

**Comment by maxrena** [comment]
I just click on "create character" and the errors pop up.

**Comment by animate1978** [comment]
Have you manually edited the base models in the humanoid.blend file at all? I did that and got similar error message.

**Comment by SleeperG** [comment]
From my understanding the json files for the base meshes have each vertex
assigned to a nearby bone. So with this in mind when you change the
position of a vertex you need to go into the json files and assign these
vertexes to the correct bone. Slepyhed1 has a tutorial on editing MBL base
meshes that explains what I'm talking about better.

**Comment by maxrena** [comment]
No, I just install the addon like normal. Then I chose "Create Character", I did not even change any settings in there.

**Comment by telnetr4** [comment]
> As a general rule, I would recommend you please do not post pictures of text error messages. Copy and paste the text itself.

Can you copy from those error pop-ups or do you have to copy it from the system console?

If the latter: you can toggle it on in Blender 2.80 by going to Window>Toggle System Console

**Comment by maxrena** [comment]
here is the log, I am using Windows 10.
Read prefs: C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: F:\Program Files (x86)\blender-2.80.0-windows64\2.80\python
Warning: class OBJECT_OT_scv_ot_draw_operator contains a properties which should be an annotation!
F:\Program Files (x86)\blender-2.80.0-windows64\2.80\scripts\modules\bpy\utils\__init__.py:669
    make annotation: OBJECT_OT_scv_ot_draw_operator.duration
Read blend: D:\Google Drive\Blender\LuanHoiblend.blend
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
Vertices database not coherent with the vertices in the obj m_as01
Traceback (most recent call last):
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\__init__.py", line 158, in check_manuelbastionilab_session
    start_lab_session()
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\__init__.py", line 103, in start_lab_session
    mblab_humanoid.init_database(obj, character_identifier, rigging_type)
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 238, in init_database
    self.init_delta_measures()
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 899, in init_delta_measures
    self.combine_morphings(modifier)
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 1128, in combine_morphings
    add_vertices_to_update)
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\morphengine.py", line 375, in calculate_morph
    self.final_form[i] = self.final_form[i] + delta*real_val
IndexError: list index out of range
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok
Vertices database not coherent with the vertices in the obj m_as01
Traceback (most recent call last):
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\__init__.py", line 1781, in execute
    start_lab_session()
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\__init__.py", line 103, in start_lab_session
    mblab_humanoid.init_database(obj, character_identifier, rigging_type)
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 238, in init_database
    self.init_delta_measures()
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 899, in init_delta_measures
    self.combine_morphings(modifier)
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 1128, in combine_morphings
    add_vertices_to_update)
  File "C:\Users\maxrena\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\morphengine.py", line 375, in calculate_morph
    self.final_form[i] = self.final_form[i] + delta*real_val
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
find_node_operation: Failed for (BONE_DONE, '')
add_relation(Copy Rotation) - Could not find op_from (OperationKey(type: BONE, component name: 'spine01.001', operation code: BONE_DONE))
add_relation(Copy Rotation) - Failed, but op_to (OperationKey(type: BONE, component name: 'abd_muscle_01_R', operation code: BONE_CONSTRAINTS)) was ok

**Comment by telnetr4** [comment]
(for future reference, select your log and press the button that looks like "<>" before commenting. That way you don't get missing characters and italics.)

I'm not 100% sure that's the entire log; I don't see anything that I usually see when starting up my Blender, but then again I have messed with the logging on my version a little. If you didn't do so, do a ctrl-a or a select all before copying to make sure you get everything.

I'm still trying to make sense of what this error means. It does look a lot like an error that gets spit out when you mess with some of the base files, but I'm not convinced that's what's causing it in this case. If I figure something out, I'll let you know.

If you haven't tried so already, I suggest reinstalling with the most up-to date version of the add-on.

**Comment by maxrena** [comment]
I have done that a lot of times. 
I reinstall the Blender to the most up-to-date version.
I do the same with ML-Lab.
It still gives out the same thing.

**Comment by animate1978** [comment]
Has this been solved? I'm going through the list trying to get things sorted.

https://github.com/animate1978/MB-Lab/issues/131#issue-451077715 is similar in the logs too, related to IK and Muscles

**Comment by maxrena** [comment]
I think yes, I have to delete everything in AppData/Local, maybe that could help
