### ISSUE TITLE
Possible spelling error

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#281]
https://github.com/animate1978/MB-Lab/blob/7855096f8c3b6fdddae8f3c41e8aee6c0f852cd2/creation_tools_ops.py#L45

Not sure at this time but it looks like this spelling error could possibly cause a bug? OR allow "forbidden" names to exist?

**Comment by TetoTheSquirrelFox** [comment]
Funny.

No I've just checked, the name is only used inside the file, not outside, and the error is everywhere.
Corrected and pushed in repository.
