### ISSUE TITLE
Toe bone flipping paste failure

### ISSUE THREAD

**Issue by millionart** [animate1978/MB-Lab#29]
**Describe the bug**
Toe bone flipping paste failure.

**To Reproduce**

1. Steps to reproduce the behavior:
2. select toes_L
3. rotate toes_L
4. copy pose (Ctrl c)
5. select toes_R
6. paste pose Flipped (Shift Ctrl v)
7. See error

**Expected behavior**
toes_R should become a mirror of L.

**Screenshots**
![-1](https://user-images.githubusercontent.com/7535532/50901996-afc14c80-1454-11e9-90ac-ef0e7d52dd9f.png)

**Additional context**
It worked fine on 1.61.

**Comment by animate1978** [comment]
Not sure how to reproduce this

**Comment by millionart** [comment]
1. select toes_L
2. rotate toes_L
3. copy pose (Ctrl c)
4. select toes_R
5. paste pose Flipped (Shift Ctrl v)

**Comment by millionart** [comment]
It's a bug not help wanted, It worked fine on 1.61 (I imported my custom pose), and other bones work fine too, only happens on toes.

**Comment by animate1978** [comment]
I've tried to reproduce this bug on my system, it doesn't seem to want to show. Could you send me a blend file with this example?

**Comment by animate1978** [comment]
OK I am understanding now, I guess I was getting the same behavior just not sure what to expect as a result. I was thinking that there was a problem that the bone did NOT flip, now I understand that you do NOT want the bone to flip on it's axis but to mirror exactly the other bone.

**Comment by animate1978** [comment]
It appears this bug was present in MB-Lab 1.6.5 too in Blender 2.79. Which is weird because until recently (72 hrs) none of the code for the armature was changed.

**Comment by animate1978** [comment]
It took a lot of searching and head scratching but I figured it out, the toes are now correctly oriented so if you repeat the steps the result should be a mirror pose.
