### ISSUE TITLE
Doubts about the license of the characters.

### ISSUE THREAD

**Issue by Malkverbena** [animate1978/MB-Lab#292]
I read the licenses but one thing was not clear.
I intend to use characters created using MB-lab to create other characters, mixing them as shapes keys. 
I intend to use this system on a game engine. All the needed code will be written on the engine.
Is this permitted by the current license? Can I use the characters created by mixing the models created from mb-lab that way in a commercial way?

**Comment by animate1978** [comment]
Unfortunately due to the way the original creator (Manuel Bastioni) had licensed the data (blend models, JSON morph library and textures) it is not possible to use in commercial works. That being said there is work being done to add, if not replace, the whole data library such as the models, JSON libs and textures but it won't be available until the code is stable AND the content is available which at this time is in a prototype state.

The JSON library is part of the AGPL3 and even if you are mixing your characters in a way that makes them different than the original model in the blend file, you are still using a AGPL3 covered library because we have yet to make new JSON libraries that are licensed in a more permissive way. There is work being done to do so but at this time again it's in a prototype stage, not ready for production use.

Hopefully this helps

**Comment by Malkverbena** [comment]
This information was very useful, thanks.
I have one more question.
If I make it available for free and under the same license, the entire blend models code, JSON morph library and code of this "character creator".
As mentioned before, I plan to use this project in a game. I have no intention of making all the game code available, but only what is related to the "Character Creator" and everything that is derived from MB-Lab.
Does this enable me to use the product commercially?

Thanks in advance

**Comment by animate1978** [comment]
I think so, as long as you provide the source files (Blend file, texture maps etc...)

Also you would need to attribute Manuel Bastioni as the original creator.

This subject has been in debate for some time, which is why we are working towards new models that have more permissive license that can be used commercially without having to provide the source files.

**Comment by Malkverbena** [comment]
I browse on issues today and noticed that.
I would love to do something about but I don't think I have useful skills to help.
Anyway, I'm going to talk to colleagues and spread it. I think that drawing attention to this project may attract some help.
Thanks for your help once again.

**Comment by splite** [comment]
> I think so, as long as you provide the source files (Blend file, texture maps etc...)

IANAL but i dont think this is how (A)GPL work - even if you release your CharacterCreator as open source, you **must** do it under (A)GPL licence (yeah, GPL is like virus) and still cant link any data from it in your game (you just moved your problem, not solved it - there isnt [Classpath exception](https://en.wikipedia.org/wiki/GNU_Classpath) in pure (A)GPL - see [GPL Linking and derived works](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works)) nor your CharacterCreator (its "infected" with (A)GPL)

So, your core game have to be without any (!) character from MB-Lab becouse you cant "link" (= bundled with) them without making your game (A)GPL.

Only way i know about is that you can pre-render every character (thats not "derivative work", you are not distributing mesh/json/etc but "projection to pixel") and use only 2d images (Again, **I AM NOT A LAWYER!** but i think i read this somewhere on Manuel Bastioni pages few years ago)

**Comment by splite** [comment]
@animate1978  @Malkverbena 

I did many edits to my previous post, so, TL;DR:

- IANAL
- MBLab models are AGPL
-  - (A)GPL is textbook example of "viral licence"
- All derived work must be AGPL (or GPL)
- - Creating "shell app" (as in "shell company", sry my engrish) under open source does not help you. Your shell app must be AGPL again. 
- - Did you linked (budled) anything with (A)GPL licence? Then your core game is derived from derived from (...) from derived AGPL, so it must be AGPL. Doesnt matter how many "hops" you add.
- (A)GPL is easily enforced by anyone. Just write email to GNU.org. You dont have to be original licence holder, you can be angry player / competitor.


What are you looking for is LGPL, MIT, CC or many others, but not (A)GPL.

If you want to write proprietary game and you do not want to violate the license, stay away from (A)GPL -> stay away from MBLab mesh. Sorry, it hurts me too.

**Comment by Malkverbena** [comment]
@splite . Thanks a lot. Your information is precious. The MBlab is an amazing tool but under this this license has become totally useless.

**Comment by Malkverbena** [comment]
@splite I notice you also a Godot user. I was working on an integration between MB-lab and Godot. A pluging to make mblab run on Godot. Anyway, it's waste of time and work.

**Comment by Atulin** [comment]
Shame about AGPL. Makes the plugin nothing more than a curiosity, ultimately not fit to use in production.

**Comment by splite** [comment]
> I notice you also a Godot user. I was working on an integration between MB-lab and Godot. A pluging to make mblab run on Godot. Anyway, it's waste of time and work.

Nice to see fellow godoter 😄
That plugin must be AGPL licenced if it use MBLab meshes/textures/database. Everything produced with him... You know the drill by now.

> Shame about AGPL. Makes the plugin nothing more than a curiosity, ultimately not fit to use in production.

Well, as i sad, i read few years agou at (now defunct) Manuel site he will not enforce licence when you use just renders. I just hope lawyers at GNU.org will believe it :)

>The way I understand it, the only way to get rid of this virus is to rewrite the format models are stored with, and provide base meshes with an open-source license?

Meshes/textures are AGPL, DB (jsons) is AGPL, this plugin is GPL (https://mblab.dev/license/)

But if meshes were, let say, LGPL or MIT licence, then you can edit them with GPL licensed sw and still pack them with your proprietary game.

So, i think the answer is yes.

(IANAL, but thats how GIMP work - GIMP is GPL, but if you edit that image of your cat you photographed on your phone, the image remains yours under whatever licence you decide it have :) But if you edit someone else image (for absurd example, you just add your watermark on screenshot of Elza) that does not mean you (nor GIMP) are magically the author and the copyright owner of Frozen)

**Comment by splite** [comment]
For further reading you can see how MakeHuman implement their licence:

http://www.makehumancommunity.org/content/license_explanation.html

MakeHuman is AGPL but it have CC-0 exception for Exported data. AFAIK MB-Lab have nothing like this exception (?) -> everything is AGPL.

**Comment by Malkverbena** [comment]
Due the fact of the licence of the models makes my projects infeasible, I am closing this issue.

**Comment by RustoMCSpit** [comment]
> That being said there is work being done to add, if not replace, the whole data library such as the models, JSON libs and textures but it won't be available until the code is stable AND the content is available which at this time is in a prototype state.

is this done? can we use it in closed source projects now? if so please add this to the readme
