### ISSUE TITLE
Resources for Link page at Wiki

### ISSUE THREAD

**Issue by NumesSanguis** [animate1978/MB-Lab#30]
You're doing a great job on improving this add-on for Blender, thank you!

I don't know how to adjust your Link page at the Wiki, but I thought this link would be useful too:
http://manuelbastionilab.wikia.com/wiki/ManuelbastioniLAB_Wiki

It's a community page I set-up when I wanted to help Manuel with his project, but I guess too few people knew about it. Not sure if that wiki should focus on this branch of MBLAB now or that it's better to only use the GitHub wiki?

I guess we can leave this issue open if other people have any suggestions for good links?

**Comment by telnetr4** [comment]
Tangentially relevant comment: I made an offline version of the original Manuel Bastioni manual just in case it goes down for some reason.

**Comment by telnetr4** [comment]
I dont think you can easily change the wiki link on Github. Animate1978 could do this, though:
https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by animate1978** [comment]
I just changed the restriction. The wiki is free to be edited, as long as it stays relevant, keep it clean, professional and the like...

**Comment by NumesSanguis** [comment]
Since the wikia link has been added and we can edit this GitHub's wiki now, I'm closing the issue.
