### ISSUE TITLE
Censorship issue

### ISSUE THREAD

**Issue by GumboCoding** [animate1978/MB-Lab#303]
Adds back censor after creating new character

**To Reproduce**
1. Create character (without censor)
2. Delete character or add a new one
3.  Censorship is back on character

**Expected behavior**
No censorship on new character

**Comment by animate1978** [comment]
There is a feature in the Addon part of the Preferences in Blender that allows you to disable the censors...

![Screenshot from 2020-12-17 08-50-29](https://user-images.githubusercontent.com/479115/102503179-12f68900-4045-11eb-8671-5cd6cf9a04e4.png)

**Comment by GumboCoding** [comment]
Thanks for responding but will it work with multiple characters?

**Comment by animate1978** [comment]
I have not tried multiple characters in a scene but theoretically it should.

**Comment by thelabcat** [comment]
You can just change the material in the slot from generic to skin.
