### ISSUE TITLE
Cannot Finalize Character

### ISSUE THREAD

**Issue by WoniJack** [animate1978/MB-Lab#305]
When clicking on Finalize Character button, get error below and does not finalize. Seems similar to bug #302 and #297. Using latest versions of Blender 2.9.1 and MB-Lab 1.7.8.42
![Screenshot 2020-10-22 161751](https://user-images.githubusercontent.com/73313118/96926197-4375d880-1483-11eb-813f-7e5bb28b9029.png)

**To Reproduce**
1. Open Blender New File
2. Click on 'MB-Lab Tab'
3. Select 'Caucasian male (M_CA01) (AGPL3)' from pull down
4. Leave defaults selected
5. Click 'Create Character' button
6. Select 'Finalize Tools'
7. Leave defaults selected
8. Click 'Finalize with textures and backup' button
9. Get the following below and does not finalize...

![Screenshot 2020-10-22 161751](https://user-images.githubusercontent.com/73313118/96925897-deba7e00-1482-11eb-96f2-9c7081cd8484.png)
**Expected behavior**
Expected character to be finalized for use.

**Additional context**
Windows 10, Blender 2.9.1, MB-Lab 1.7.8.42
I have tried reinstalling Blender, reinstalling MB-Lab but still get error.

**Logs**

Traceback (most recent call last):
  File "C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\__init__.py", line 1703, in execute
    mblab_humanoid.set_rest_pose()
  File "C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\humanoid.py", line 1266, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py", line 1069, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized
location: <unknown location>:-1
location: <unknown location>:-1

**Comment by pupnsuds** [comment]
The method in question bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name) No longer exists in Blender 2.9. It is now bpy.ops.object.modifier_apply(modifier=modifier_name)
ShapeKey also has it's own method.

You can fix this locally by editing your algorithms.py file to use the new modifier_apply method until it is officially fixed and merged to support 2.9. Your file is located here C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py. You will need to restart blender after the edit. 


The my new method; looks like this.

def apply_modifier(obj, modifier):
    modifier_name = get_modifier_name(modifier)
    if modifier_name in obj.modifiers:
        set_active_object(obj)
        try:
            bpy.ops.object.modifier_apply(modifier=modifier_name)
        except AttributeError:
            logger.warning("Problems in applying %s. Is the modifier disabled?", modifier_name)

**Comment by WoniJack** [comment]
Thank you, this seems to work!

**Comment by Starkium** [comment]
You're my hero

**Comment by WARW0LF** [comment]
> Looks like a duplicate of bug #297
> Check the thread for answers
> 
> Here is how I fixed it for now in 2.9
> 
> The method in question bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name) No longer exists in Blender 2.9. It is now bpy.ops.object.modifier_apply(modifier=modifier_name)
> ShapeKey also has it's own method.
> 
> You can fix this locally by editing your algorithms.py file to use the new modifier_apply method until it is officially fixed and merged to support 2.9. Your file is located here C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py. You will need to restart blender after the edit.
> 
> The my new method; looks like this.
> 
> def apply_modifier(obj, modifier):
> modifier_name = get_modifier_name(modifier)
> if modifier_name in obj.modifiers:
> set_active_object(obj)
> try:
> bpy.ops.object.modifier_apply(modifier=modifier_name)
> except AttributeError:
> logger.warning("Problems in applying %s. Is the modifier disabled?", modifier_name)

Thanks you so much

**Comment by nameless667** [comment]
Hey team! I've been trying to apply the fix above to algorithms.py but I guess something breaks and the addon disappears from the N panel on next load (2.90 and 2.91). Any pointers for a newb?

**Comment by animate1978** [comment]
The recent pull requests to 'master' should resolve this issue
