### ISSUE TITLE
Can't Finalize, type error

### ISSUE THREAD

**Issue by J3Studios** [animate1978/MB-Lab#308]
Hello I am getting this error when I try to finalize my character.

Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-1_7_8\__init__.py", line 1703, in execute
    mblab_humanoid.set_rest_pose()
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-1_7_8\humanoid.py", line 1266, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-1_7_8\skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-1_7_8\algorithms.py", line 1069, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

I am new to blender and to this new addon.

**Comment by gogobd** [comment]
Same error Blender 2.90.1, MB Lab 1.7.8.42, macOS Big Sur

**Comment by frostyclimes** [comment]
Same error Blender 2.91, MB Lab 1.7.8.42m, Win 10 Pro (latest)
I am also unable to save images and backup character - file is in the ether somewhere.

**Comment by JMB702** [comment]
I'm having the same issue. I'm using macOS Catalina, Blender 2.90.1 MB-Lab 1.7.8.42. It has kind of brought me to a standstill in using this addon.

**Comment by frostyclimes** [comment]
I discovered (maybe I read the manual?) where it says 'do not make any changes to the model in edit mode' or you will get errors. It worked for me. Now today, I've changed the name of the skeleton on another model before finalizing and got the error again. So, just stay in object mode and 'do nothing else' but get it how you want it there, until you're ready to finalize.

**Comment by frostyclimes** [comment]
Further to this, it appears the error occurs when IK is 'not' selected. Line 1703.

**Comment by thelabcat** [comment]
I fixed it by just manually removing that argument, suspecting that it was obsolete in 2.91. No apparent consequences.

**Comment by frostyclimes** [comment]
I'll give that a try. Thx

**Comment by RahaKodesh** [comment]
Hey Guy I was getting a huge error as well, All i did was #1 Save a copy of the Blender File 1st so you have an Orginal, And # 2 Just go and apply all your modifiers and that was it, I was able to export. Looks like the MBLAB is just trying to apply the Mods before exporting, but something is Looping. Try let me know if it works for yall. Thanks

**Comment by thelabcat** [comment]
Well, yeah, you can do that, but then the final only tools like face rigging and hair aren't available. That's why one needs the code.

**Comment by animate1978** [comment]
Hey guys, sorry for the long absence it wasn't supposed to take this long... I just got internet service yesterday.

I will look over things and start to do some changes.

**Comment by animate1978** [comment]
The recent pull requests to 'master' should resolve this issue
