### ISSUE TITLE
Finalization not working in 2.91

### ISSUE THREAD

**Issue by thelabcat** [animate1978/MB-Lab#309]
**Describe the bug**
Attempting to finalize a character raises an error in blender 2.91. The error occurred when the script tried to apply the character's modifiers, being raised from the keyword argument "apply_as='DATA'" at line 1069 of algorithms.py, said keyword apparently being obsolete in the blender 2.91 api.

Manual removal of this keyword argument from the code stopped the error without any apparent negative consequences.

**Comment by animate1978** [comment]
The recent pull requests to 'master' should resolve this issue
