### ISSUE TITLE
Can not create hair from After-Creation Tools

### ISSUE THREAD

**Issue by SandMan113** [animate1978/MB-Lab#310]
**Describe the bug**
I can't create particle hair from the after creation tools menu. I am getting an error.

**To Reproduce**
With a finalized character, go to "Assets and Hair" menu, then click "Particle Hair". Error occurs there.

**Expected behavior**
Particle hair should be created.

**Screenshots**
![MBLabError](https://user-images.githubusercontent.com/76236478/102679555-94056b80-417e-11eb-9f0e-6538e013443b.png)

**Comment by thelabcat** [comment]
I did not have this problem. Did you delete the armature or something similar? (Can't zoom in on the screenshot in mobile 😅)

**Comment by SandMan113** [comment]
I did not. Everything is there.

Seems like something is wrong with that particular file, as quickly making another character does allow me to use particle hair. I tried importing the data from that character to a new file and now it is working.

**Comment by thelabcat** [comment]
😌 oh, good.
