### ISSUE TITLE
Finalize not working in Blender 2.9.1

### ISSUE THREAD

**Issue by mannojkumarr** [animate1978/MB-Lab#311]
File "C:\Users\manno\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\__init__.py", line 1703, in execute mblab_humanoid.set_rest_pose() File "C:\Users\manno\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\humanoid.py", line 1266, in set_rest_pose self.sk_engine.apply_armature_modifier() File "C:\Users\manno\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\skeletonengine.py", line 119, in apply_armature_modifier algorithms.apply_modifier(obj, armature_modifier) File "C:\Users\manno\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\algorithms.py", line 1069, in apply_modifier bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name) File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__ ret = _op_call(self.idname_py(), None, kw) TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized location: <unknown location>:-1

**Comment by mannojkumarr** [comment]
I Found the solution just edit
You can fix this locally by editing your algorithms.py file to use the new modifier_apply method until it is officially fixed and merged to support 2.9. Your file is located here C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py. You will need to restart blender after the edit.

https://github.com/animate1978/MB-Lab/pull/306/commits/223bf9daaf1885f2e73ae461b3572bb2b4ed4d0e

**Comment by aniruddhahar** [comment]
Thanks for this fix. Here are some more details in case anyone is looking for what exactly to change. Open algorithms.py located here: 
%AppData%\Roaming\Blender Foundation\Blender\2.90\scriptts\addon\MB-Lab<version>\algorithms.py

Find this line, in the apply_modifier method definition:
`bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)`

change it to:
`bpy.ops.object.modifier_apply(modifier=modifier_name)`

And this should get finalize working again. Restart blender if it's open.

> 
> 
> I Found the solution just edit
> You can fix this locally by editing your algorithms.py file to use the new modifier_apply method until it is officially fixed and merged to support 2.9. Your file is located here C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py. You will need to restart blender after the edit.
> 
> [223bf9d](https://github.com/animate1978/MB-Lab/commit/223bf9daaf1885f2e73ae461b3572bb2b4ed4d0e)

**Comment by animate1978** [comment]
The recent pull requests to 'master' should resolve this issue

**Comment by DakotaRUS** [comment]
> Thanks for this fix. Here are some more details in case anyone is looking for what exactly to change. Open algorithms.py located here:
> %AppData%\Roaming\Blender Foundation\Blender\2.90\scriptts\addon\MB-Lab\algorithms.py
> 
> Find this line, in the apply_modifier method definition:
> `bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)`
> 
> change it to:
> `bpy.ops.object.modifier_apply(modifier=modifier_name)`
> 
> And this should get finalize working again. Restart blender if it's open.
> 
> > I Found the solution just edit
> > You can fix this locally by editing your algorithms.py file to use the new modifier_apply method until it is officially fixed and merged to support 2.9. Your file is located here C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py. You will need to restart blender after the edit.
> > [223bf9d](https://github.com/animate1978/MB-Lab/commit/223bf9daaf1885f2e73ae461b3572bb2b4ed4d0e)

Thx, it helped

**Comment by ajithveee** [comment]
> Thanks for this fix. Here are some more details in case anyone is looking for what exactly to change. Open algorithms.py located here: %AppData%\Roaming\Blender Foundation\Blender\2.90\scriptts\addon\MB-Lab\algorithms.py
> 
> Find this line, in the apply_modifier method definition: `bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)`
> 
> change it to: `bpy.ops.object.modifier_apply(modifier=modifier_name)`
> 
> And this should get finalize working again. Restart blender if it's open.
> 
> > I Found the solution just edit
> > You can fix this locally by editing your algorithms.py file to use the new modifier_apply method until it is officially fixed and merged to support 2.9. Your file is located here C:\Users\jeffl\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MB-Lab-master\algorithms.py. You will need to restart blender after the edit.
> > [223bf9d](https://github.com/animate1978/MB-Lab/commit/223bf9daaf1885f2e73ae461b3572bb2b4ed4d0e)

Thanks Worked for Blender 3.0

**Comment by SyphoneHub** [comment]
Hi, I was wondering how do I get to the python file, like where do I put in the: %AppData%\Roaming\Blender Foundation\Blender\2.90\scriptts\addon\MB-Lab\algorithms.py ? I haven't coded anything in blender before and I've looked for videos but the closest they got was just showing the file, not how to search for it, if you could help that'd be great.

**Comment by ldo** [comment]
Normally you don’t go putting in files by hand, particularly if you don’t know what you’re doing!

Download the complete `.zip` file from the [releases page](https://github.com/animate1978/MB-Lab/releases), and [follow the usual instructions](https://docs.blender.org/manual/en/latest/editors/preferences/addons.html#installing-add-ons) for installing.

**Comment by SyphoneHub** [comment]
well I mean can you just explain the process of how you got to the point of editing it, like what you open to put the %AppData%\Roaming\Blender Foundation\Blender\2.90\scriptts\addon\MB-Lab\algorithms.py Thats what I mean if that's any clearer

**Comment by SyphoneHub** [comment]
ok i figured it out, but when i went into addon i dont see mb-lab, using 3.0 btw

**Comment by enamnoeki** [comment]
Thank you. This helped me
