### ISSUE TITLE
Joints creation produces a half scale skeleton

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#318]
**Describe the bug**
When creating the joints for Toon Girl, the final output produces a skeleton that is much smaller than intended.

![screenshot_12_12_20](https://user-images.githubusercontent.com/479115/103455105-a4096900-4caf-11eb-9b98-cae0e7e021c2.png)

**Expected behavior**
Scaled correctly skeleton

**ZIP file**

This is a ZIP archive of the current Toon Girl build, to test out this issue.

[TOONGIRL.zip](https://github.com/animate1978/MB-Lab/files/5760090/TOONGIRL.zip)

**Comment by Upliner** [comment]
you just need to apply transforms of the toon girl in humanoid_library.blend

**Comment by animate1978** [comment]
OK figured out the issue, thank you @Upliner for the tip. It did in fact rescale to correct height compared to the rest of the MB-Lab meshes... I think I can close this issue now.
