### ISSUE TITLE
Can't Finalize

### ISSUE THREAD

**Issue by Patrick1358** [animate1978/MB-Lab#319]
I use the latest versions of Blender (2.91.0) and MB-Lab (1.7.8) and i can't finalize my character while these settings are applied:

![image](https://user-images.githubusercontent.com/37535840/103648351-6b92b500-4f65-11eb-98ac-6a048c53c742.png)

or 

![image](https://user-images.githubusercontent.com/37535840/103648435-8e24ce00-4f65-11eb-9992-67a0c3a85e41.png)

If i have these settings applied i can finalize my character without any issues:

![image](https://user-images.githubusercontent.com/37535840/103648513-ac8ac980-4f65-11eb-893d-95b85a204e0c.png)

or

![image](https://user-images.githubusercontent.com/37535840/103648545-b7455e80-4f65-11eb-88aa-f36c874beb30.png)

P.S.: I tried the MB-Lab fix from Github and i can't activate/turn on the addon even if i have a fresh install of Blender and/or MB-Lab.

The error follows as:

Python: Traceback (most recent call last):
  File "C:\Users\imali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\__init__.py", line 1703, in execute
    mblab_humanoid.set_rest_pose()
  File "C:\Users\imali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\humanoid.py", line 1266, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "C:\Users\imali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "C:\Users\imali\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\algorithms.py", line 1069, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by animate1978** [comment]
That is very strange. Are you downloading a ZIP of the addon? Or are you pulling the source using Git?

**Comment by Patrick1358** [comment]
Downloaded the .ZIP file from Git

**Comment by animate1978** [comment]
Ahh... yeah that one on the website has not had it's code updated, that was released before the recent code changes to make the 'master' branch compatible with Blender 2.91. I would suggest that you delete the addon then download the ZIP from here and use that instead.

**Comment by Patrick1358** [comment]
Sure thing. Tested and works fine now, didn't knew that that was the issue.
Thank you for your time and help.

**Comment by thelabcat** [comment]
Wait, github is ahead of the website? Which version does the addon's updater check?

**Comment by animate1978** [comment]
The addon updater always checks GitHub

**Comment by Patrick1358** [comment]
I don't recall that. I tried updating the addon from Blender and it said it was up to date (while the issue was "active").
