### ISSUE TITLE
No shape keys in finalized character in 2.91

### ISSUE THREAD

**Issue by steveday4u** [animate1978/MB-Lab#325]
**Describe the bug**
When using the plugin in blender 2.91 finalizing the character does not work

**To Reproduce**
finalize a character. There are no post creation tools available. all shape keys are missing
**Expected behavior**
options should be available, facial keys should be present in finalized character

I tried 1.7.7b and 1.7.8. they are having the same problem. in 1.7.8 the ui seems also broken (all ui expansions are created at the bottom).

**Comment by steveday4u** [comment]
ok, fixed it myself:

in MB-Lab/algorithms.py -> apply_modifier
       
```
        try:
            if bpy.app.version >= (2, 91, 0):
                bpy.ops.object.modifier_apply(modifier=modifier_name)
            else:
                bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
        except AttributeError:
            logger.warning("Problems in applying %s. Is the modifier disabled?", modifier_name)
```

**Comment by animate1978** [comment]
Ahh yes this was fixed in the recent push to the repo.... it is the 'master' branch of MB-Lab

**Comment by steveday4u** [comment]
that whould have been a great opportunity for a bugfix release...
