### ISSUE TITLE
Error when finalizing a female elf 2.91

### ISSUE THREAD

**Issue by OGDragonDM** [animate1978/MB-Lab#327]
MB-lab + Blender 2.91.2 both freshly downloaded today. Customize the female elf model and go to finalize. 
I get this error, which means nothing to me but might mean something to someone more savvy.
---------------------
Python: Traceback (most recent call last):
  File "C:\Users\44788\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab-master\__init__.py", line 1698, in execute
    armature = mblab_humanoid.get_armature()
  File "C:\Users\44788\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab-master\humanoid.py", line 345, in get_armature
    return self.sk_engine.get_armature()
AttributeError: 'Humanoid' object has no attribute 'sk_engine'

location: <unknown location>:-1

-----------------------------

**Comment by animate1978** [comment]
Hey there,

So I literally JUST updated the download link on the website.... you may be running the older version of 1.7.8... 

This can be downloaded directly here 

https://mblab.dev/download/mb-lab-1-7-8-5/#

However I am using Blender 2.91.0 so there may be something else wrong I am going to test that as soon as the download finishes

**Comment by OGDragonDM** [comment]
> Hey there,
> 
> So I literally JUST updated the download link on the website.... you may be running the older version of 1.7.8...
> 
> This can be downloaded directly here
> 
> https://mblab.dev/download/mb-lab-1-7-8-5/#
> 
> However I am using Blender 2.91.0 so there may be something else wrong I am going to test that as soon as the download finishes
--------------------------------------
You are a legend thanks, downloading and will be trying in a  few hours when I get free.
