### ISSUE TITLE
Female Elf hair source is bazerk

### ISSUE THREAD

**Issue by thelabcat** [animate1978/MB-Lab#343]
**Describe the bug**
![image](https://user-images.githubusercontent.com/53358500/112365940-9cee6780-8cae-11eb-901c-00a54294eb67.jpeg)

**To Reproduce**
1. Create and finalize a female elf.
2. Select the mesh.
3. Create MB-lab hair.
4. The hair source mesh stays to the top of her body, but no other standard. Not even symmetrical.

**Additional context**
I have never tried adding hair to an elf before, so this may not be new. I updated recently.

**Logs**
No logs apparently relative to problem: No errors were generated.

**Comment by thelabcat** [comment]
**Close this issue as invalid.** I made some edits to the mesh but must've done it before I finalized. Did the whole thing from scratch with pure vanilla defaults, and no error.

**Comment by animate1978** [comment]
Ok.
