### ISSUE TITLE
Enabling mb-lab crashes blender 2.92

### ISSUE THREAD

**Issue by LimaneGaya** [animate1978/MB-Lab#345]
**Describe the bug**
installing mb-lab with no issue but enabling it crashes blender. 

**To Reproduce**
1. Install the addon.
2. Enabling it.

**Expected behavior**
A crash of blender.

**Additional context**
Blender is installed as a snap.
OS: kubuntu 20.10

**Comment by thelabcat** [comment]
Huh, that is odd. Can confirm that unless MBL was updated and I wasn't notified, this is an OS specific issue.

**Comment by animate1978** [comment]
No MB-Lab was not modified. I actually have Ubuntu 20.10 installed on my system BUT Blender is not installed as a Snap. I will look into this somehow.

**Comment by LimaneGaya** [comment]
I tried to get the log file to see what's causing the issue.

CPU flags:
  AVX2       : True
  AVX        : True
  SSE4.1     : True
  SSE3       : True
  SSE2       : True
  BVH layout : EMBREE
  Split      : False
CUDA flags:
  Adaptive Compile : False
OptiX flags:
  CUDA streams : 1
OpenCL flags:
  Device type    : ALL
  Debug          : False
  Memory limit   : 0
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr5, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr2 = V_CNDMASK_B32_e32 32768, killed $vgpr2, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
Aborted (core dumped)

**Comment by LimaneGaya** [comment]
The issue seem to be related to blender 2.92 as it's working fine on 2.93.
