### ISSUE TITLE
TEXTURE BAKE AND EXPORT MODEL WITH TEXTURE FOR GAME ENGINE AND OTHER USE 

### ISSUE THREAD

**Issue by kainatquaderee** [animate1978/MB-Lab#365]
THERE IS NO TEXTURE IN EXPORTED FILE. I TRIED TO EXPORT WITH THE TEXTURE OPTION IN BLENDER BUT IT DIDN'T WORK I NEED A TEXTURE BAKING TO EXPORT IT WITH TEXTURE PLZ ADD THAT FEATURE OTHERWISE IT WILL BE VERY HARD TO USE IN THE GAME ENGINE. THANK YOU FOR CREATING THIS VERY POWERFUL CHARACTER CREATOR. FOR USE IN BLENDER IT IS SUPPER GOOD BUT TEXTURE FEATURE SHOULD BE ADDED TO USE IT OUTSIDE.

**Comment by bmourit** [comment]
For game engines, exporting from blender usually requires you to copy your textures separately. embedding them in the .fbx export isn't usually something that works for me.
Regardless, this isn't a MB-Lab issue. The textures are all there with the plugin. What you do with them/how you use them is up to you and varies person to person.

**Comment by thelabcat** [comment]
I WOULD LIKE TO CALMLY SUGGEST THAT YOU NOT USE SHOUTY CAPS WHEN TYPING. IT MAKES PEOPLE LESS MOTIVATED TO HELP YOU WHEN THE FIRST THING YOU SAY IS LOUD.
