### ISSUE TITLE
FACS Rig Usage

### ISSUE THREAD

**Issue by Choons** [animate1978/MB-Lab#370]
I created a character with the FACS rig imported, but I can't seem to make it do anything. I've searched a few hours now, but haven't found anything very helpful other than passing mention of it in the documentation. How does one use the MB-Lab FACS rig?

I'm running Blender 2.93 on Ubuntu, in case that's useful.

**Comment by Upliner** [comment]
What's the problem with it? Just grab sliders and move them. But you need to be in object mode.

**Comment by Choons** [comment]
OK it works. I was trying to select the whole thing expecting it to highlight-- ya know like the way the rest of the rig works?
