### ISSUE TITLE
Expressions shape keys origin?

### ISSUE THREAD

**Issue by Choons** [animate1978/MB-Lab#371]
I noticed the phoneme and FACS rigs work by modifying the Expressions shape keys. Are those Expressions shape keys from a standard set, or are they unique to MB-Lab? I'm trying to make lip sync look as natural as possible and am gathering as much info as I can before I start.

**Comment by Upliner** [comment]
I think they're unique to MB-Lab. And what is the "standard set" you're talking about?

**Comment by Choons** [comment]
I mean like how FACS and phonemes are standardized. I'm wondering if Manuel used a standard set of shape keys (morph targets) to make the Expressions in MB-Lab, or if those are custom made.

**Comment by Upliner** [comment]
As I see MB-Lab has it's own set that partially intersects with FACS.

**Comment by Choons** [comment]
Gotcha. I like the notion of FACS, but I think they went too far with it. Too many intermediate action units. I'd rather just have the face muscle movements from zero to max flex. Thanks for the prompt replies!
