### ISSUE TITLE
Licensing of derivative models

### ISSUE THREAD

**Issue by Calandiel** [animate1978/MB-Lab#375]
In #215 it was pointed out that the AGPL licensed models are, well, AGPL licensed and thus their licensing is viral. How would that apply, however, to derivative models? Let's say that some model was retopologized, for example with Blenders voxelization utilities. Could such a model be licensed under a different license or would that count as a derivative of the base AGPL model?
What about models constructed from renders? There are ways to create topologies out of as few as 3 images from different angles.

**Comment by Hopefullyidontgetbanned** [comment]
derivative  models are completely above board however most of the community members simply made a solution by creating [Charmorph ](https://github.com/Upliner/CharMorph)which has "Reom" which only requires attribution  and is 100% commercial friendly.
You can become a part of the discord community while you're at it.

**Comment by Calandiel** [comment]
Interesting. I wasn't aware of that tool but by the looks of it, it won't be suitable for my use case. I'm looking for characters roughly in the shojo manga style and partially as targets for further sculpting ^^

**Comment by pedroalmeida415** [comment]
@Calandiel would love to know a little more about your experience using it for the purpose of achieving anime/manga character looks, I just found out about this and it looks very promising

Thanks in advance

**Comment by Calandiel** [comment]
> @Calandiel would love to know a little more about your experience using it for the purpose of achieving anime/manga character looks, I just found out about this and it looks very promising
> 
> Thanks in advance

I use hand made models now. Sorry for a disappointing answer. If you want a similar esque tool, I suggest using VRoid instead. Though, that's not really following the subject of the issue anymore, is it.

I'll close it since the original question was answered.
