### ISSUE TITLE
not working properly on blender 4.0.1

### ISSUE THREAD

**Issue by soykhaler** [animate1978/MB-Lab#395]
I can't finalize character to adding clothes and hair on blender 4.0.2, i got this error message when i pressed "Finalize with textures and backup"

![image](https://github.com/animate1978/MB-Lab/assets/74861088/a7464d7e-4a27-45a9-957a-dfe6c5dda4dd)

**Comment by animate1978** [comment]
The current master build of MB-Lab will not function in Blender 4, not without some work. I have been fixing the code on my end and will be pushing it in the upcoming days / weeks.

**Comment by animate1978** [comment]
You can find a beta developmental version here : https://github.com/animate1978/MB-Lab/tree/4_0_dev_branch
