### ISSUE TITLE
does not work for blender 4.0

### ISSUE THREAD

**Issue by bharatbhatt762** [animate1978/MB-Lab#398]
![Screenshot (161)](https://github.com/animate1978/MB-Lab/assets/38124293/7f6a9c7a-12c8-4caa-9a35-3c3fd796e2ad)
Body Measures drop down gives error after character is made .**Describe the bug**

**To Reproduce**

**Expected behavior**
options for body parts as ears, eyes etc do not appear (
![Screenshot (161)](https://github.com/animate1978/MB-Lab/assets/38124293/b8c06c7d-ec32-4b2e-a63e-918dc8f7215b)
which should appear)

**Screenshots**

**Additional context**

**Logs**
`To format it correctly, logs should go in between these:`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.

**Comment by thecuriousorange** [comment]
I encountered this issue, I believe it just needs 2 lines of code changing in object_ops.py.
I extracted the file from the MB-Lab-master.zip, opened the file in a soucecode editor (although you could use notepad or similar), searched for np.bool and replaced it with bool. there were 2 instances of it. I then put the file back into the MB-Lab-master.zip file and overwrote the original. removed the installed addon version, and installed from the fixed version.

here is a gist: https://gist.github.com/thecuriousorange/a823e3eb952fd90fb11c1375eb261213 of what I did
