### ISSUE TITLE
Skin Shader Improvements

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#4]
Ver 1.6.1a (Manuel's last version) was good but upon some playing around, added another layer of SSS for 1.6.2. Right now testing with 3 layers of SSS, with a sub dermal texture map input, also have a temp texture map for this, to try to achieve an even better skin look than before.

Possible texture bump map inputs for pores , wrinkles and other skin features.

**Comment by animate1978** [comment]
![3_layer_sss_new_skin_bump_005](https://user-images.githubusercontent.com/479115/49651727-a11aec00-f9f5-11e8-9849-b36bd2a6bfe0.png)

Modified the bump mapping in the skin shader, now has procedural pores and skin cells based off of Voronoi textures. Minor edits to shader network to properly show bump mapping. This also has three layers of SSS.

**Comment by animate1978** [comment]
![3_layer_sss_new_skin_bump_006_scaled](https://user-images.githubusercontent.com/479115/49689920-1f5ab980-faee-11e8-9526-29467734365d.png)

Using image based lighting to see how the skin shader would react to real world lighting conditions rather than the studio lighting setup by MB-Lab.

**Comment by animate1978** [comment]
![3_layer_sss_new_skin_freckles_001_scaled](https://user-images.githubusercontent.com/479115/49880305-77950280-fdf1-11e8-91e4-dc7c627676a6.png)

Added a procedural freckle network. The above image has the freckles shaded blue to enhance where they would be located while working on the nodes.

![3_layer_sss_new_skin_freckles_002_scaled](https://user-images.githubusercontent.com/479115/49880466-d8bcd600-fdf1-11e8-82f5-033eee0eb170.png)

The above image has the freckles as a more normal color.

**Comment by animate1978** [comment]
Version 1.6.5 is almost ready with a whole new shader network based off of **Principled BSDF**. This includes

- New Texture Maps for specular and sub dermal.
- Additional code to load new texture maps to the correct image texture node.
- References to new texture maps in character config file for all character types
- Skin Editor changes to reflect new shading network

Update and point release to happen this weekend. (went a lot faster than expected)

**Comment by animate1978** [comment]
![pbr_shader_ver1_6_5_004](https://user-images.githubusercontent.com/479115/50327527-20f48c00-04b5-11e9-8bb1-c0e18ad5ee29.png)

A recent render using the 1.6.5 shader

**Comment by animate1978** [comment]
Added Roughness node and updated humanoid library for females at this time, working on males next.

Minor shader node tweak of Skin Value

**Comment by animate1978** [comment]
![screenshot_2018-12-23_10-15-29](https://user-images.githubusercontent.com/479115/50385474-e00a9c00-069b-11e9-9d57-b7ea14b636de.png)

Added Scale to Subsurface Radius, so now SSS can be scaled again in Principled BSDF. Will commit after the holidays.

**Comment by animate1978** [comment]
Going to be re-visiting the shader network soon, according to a user my shader work is good but it's not correct in modern terms of CG. It kind of ties in with the texture maps as well.

Since the maps and the shader work hand in hand....

**Comment by animate1978** [comment]
Shaders have been worked on, now instead of "Diffuse", it is now "Albedo". This is due to shader terminology changing in the field, an albedo map is simply a color map where as Diffuse is generally considered a shading method. Really did not think about it too much until a user brought this up to my attention, so I made some changes regarding this. This applies to ALL models and shaders.

**Comment by NumesSanguis** [comment]
Is this renaming from Diffuse to Albedo the reason for this issue?:
https://github.com/animate1978/MB-Lab/issues/87

**Comment by animate1978** [comment]
Yes, it was a typo that I failed to check before pushing to the repo, it has been fixed this morning.

**Comment by animate1978** [comment]
Been some time since the skin shader has been worked on, some things have been neglected far too long and in general the shader needed some work.

So the plan is to do away with Principled as the "skin" and to go back to a custom SSS node group, the reasoning behind this is because it simply looks better. There is more control over the skin layers than in Principled and MOST people use custom nodes for skin anyway...
So work is underway for the next version of MB-Lab (1.7.4) to have a whole new skin shader.

Procedural veins have been added, though the cool thing about them is that they do not use color, it uses an Overlay blend so that they can change color with skin hue. User controls for the skin editor have yet to be added to the shader but the node group is there and looks good.

The freckles have long been neglected, so they have been reworked slightly and now use a mask so that they only are dense in certain areas (currently only the face, around the nose). While small freckles will appear elsewhere it's not so obvious and does not look as fake as before.

Will be posting some images in near future as the shader progresses.

**Comment by animate1978** [comment]
Been some time since the skin shader has been worked on, some things have been neglected far too long and in general the shader needed some work.

So the plan is to do away with Principled as the "skin" and to go back to a custom SSS node group, the reasoning behind this is because it simply looks better. There is more control over the skin layers than in Principled and MOST people use custom nodes for skin anyway...
So work is underway for the next version of MB-Lab (1.7.4) to have a whole new skin shader.

Procedural veins have been added, though the cool thing about them is that they do not use color, it uses an Overlay blend so that they can change color with skin hue. User controls for the skin editor have yet to be added to the shader but the node group is there and looks good.

The freckles have long been neglected, so they have been reworked slightly and now use a mask so that they only are dense in certain areas (currently only the face, around the nose). While small freckles will appear elsewhere it's not so obvious and does not look as fake as before.

Will be posting some images in near future as the shader progresses.

**Comment by animate1978** [comment]
![new_skin_04](https://user-images.githubusercontent.com/479115/54751506-33ac5900-4ba9-11e9-915a-b8b3af3254e5.png)

**Comment by animate1978** [comment]
![new_skin_021](https://user-images.githubusercontent.com/479115/55081324-a0be6380-506d-11e9-8fcf-18b803f16002.png)

This is a preview of the new skin shader.

A more detailed breakdown of what has been added or changed will happen when the shaders are uploaded to Dev.

**Comment by animate1978** [comment]
![new_shaders_003_edit](https://user-images.githubusercontent.com/479115/55293615-e9538500-53bd-11e9-85af-8cd55207ba46.png)

Another preview, this is with the eyes being full procedural. They need work but on the right track.

**Comment by animate1978** [comment]
Procedural eyeballs have been scrapped due to mapping errors when changing character parameters. I never checked beyond the default model until this morning....

**Comment by animate1978** [comment]
OK so after some testing I will be re-assigning materials to polygons of the eyeball, the pupil needs some work and the iris needs to be defined but doing it this way will work.

**Comment by NumesSanguis** [comment]
With the latest Blender 2.8 (2019-04-20) and MB-Lab v1.7.4, the procedural eye shader seems broken for Cycles, ViewPort and EEVEE. Please see the image.

![MBlab174_weird-eye](https://user-images.githubusercontent.com/8008618/56454058-62734600-6386-11e9-9b6d-2a8d07487082.png)

**Comment by animate1978** [comment]
After some troubleshooting it looks like the Glossy node in the cornea shader is set to black, where as in my Dev file it is set to a value of 0.500.

See if this will fix the issue of it looking weird?

**Comment by animate1978** [comment]
So have officially begun to work on the new tongue shader.

WIP

* Shader itself - this requires at least these nodes : Albedo, SSS, Bump

* MaterialEngine.py - Requires editing to load up textures into new nodes
* character_config.json - Ties it all together for each base model, what to name new entries?????

**Comment by animate1978** [comment]
Worked on it for a couple of hours, initial tongue shader added to Dev branch

**Comment by animate1978** [comment]
FACEPALM - forgot to add this to the Human Male!!

**Comment by animate1978** [comment]
![bumpmap_options_01](https://user-images.githubusercontent.com/479115/59964595-527ffb80-94c8-11e9-8062-a91fb0f207d8.png)

Working on the bump map. Not sure if I want to use an edited version, or just an inverted version.

The larger of the maps is the edited, while the inverted is the smaller one.

**Comment by animate1978** [comment]
![Screenshot from 2019-06-26 09-17-18](https://user-images.githubusercontent.com/479115/60187521-575bec80-97f3-11e9-948b-acc7c10d461b.png)

I also noticed that I never finished the male bump map, the eyes have been painted over but the nose has not. So that needs to be fixed for this release.

**Comment by animate1978** [comment]
![human_female_bump](https://user-images.githubusercontent.com/479115/60260046-3a302800-989e-11e9-8b25-a88907b4eef4.png)
![human_male_bump](https://user-images.githubusercontent.com/479115/60260047-3a302800-989e-11e9-8ee4-a8357f3606ea.png)

A preview of the new maps before committing to Dev

**Comment by animate1978** [comment]
![MBLAB_SKIN_VER2_0](https://user-images.githubusercontent.com/479115/61680688-3393a580-acd0-11e9-9ad9-4c4247baaf05.png)

Working on a new shader for skin, that may or may not be replacing the current model in the near future.

**Comment by animate1978** [comment]
Since I am working on Version 2 of the skin shader I think I am going to close this issue since there is no need to have duplicate issues about skin shaders.
