### ISSUE TITLE
Export option for game engine

### ISSUE THREAD

**Issue by LimaneGaya** [animate1978/MB-Lab#412]
**Is your feature request related to a problem? Please describe.**
This feature would be a great add to MB-Lab.

**Describe the solution you'd like**
This is a feature request for adding export option for game engines, the option should bake PBR textures used in game engines.

**Comment by seenbuklee** [comment]
Hate to break it to you, but the project is no longer being maintained
https://github.com/animate1978/MB-Lab/discussions/410

**Comment by LimaneGaya** [comment]
Well that's a disappointment, i finally got to chose between makehuman and mb-lab and i find out it's unmaintained.
it's cool i understand the dev point of view, i'll check charmorph next.
Anyway, thanks @Hopefullyidontgetbanned for letting me know it's not longer maintained.
