### ISSUE TITLE
Proxy Fitting broken

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#46]
**Describe the bug**
Proxy fitting does not work. Will also remove armature from the mesh.

**To Reproduce**

1. Create character
2. Finalize
3. Load up an asset.
4. Go to Proxy Fitting
5. Check 'Transfer Weights..."

This error is produced -

```

Material MBlab_generic has not nodes
Removing  mbastlab_mask_hair01_human_female
Traceback (most recent call last):
  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\__in
it__.py", line 1588, in execute
    mblab_proxy.fit_proxy_object(offset, threshold, scn.mblab_add_mask_group, scn.mblab_transfer_pro
xy_weights)
  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\prox
yengine.py", line 358, in fit_proxy_object
    self.transfer_weights(body, proxy)
  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\prox
yengine.py", line 75, in transfer_weights
    w_data.append([grp.name, grp.weight(idx)])
RuntimeError: Error: Vertex not in group


location: <unknown location>:-1

location: <unknown location>:-1


```
![proxy_fitting_bug01](https://user-images.githubusercontent.com/479115/51070435-b98ab180-1606-11e9-90d2-2153bd70187e.png)

I moved the armature around to show example of breakage.

THEN

Repeat steps above but uncheck the 'Transfer Weights..." box and it still breaks the armature.

![proxy_fitting_bug](https://user-images.githubusercontent.com/479115/51070369-b5aa5f80-1605-11e9-9d21-58a5ca166f3e.png)

**Expected behavior**
The proxy is supposed to fit the mesh and the armature is supposed to stay with the mesh.

This is a serious bug.

**Comment by animate1978** [comment]
Well it no longer throws up an error but the Proxy Fitting still breaks the armature of the character

**Comment by dvdmgl** [comment]
@animate1978 was it previous doing that?

**Comment by animate1978** [comment]
Yes. When the error popped up the armature was removed from the mesh as well

**Comment by animate1978** [comment]
Reverted proxyengine.py to 1.7.0 version, with logging added
