### ISSUE TITLE
Having trouble Downloading add-on

### ISSUE THREAD

**Issue by HoboJoeFish** [animate1978/MB-Lab#54]
I am having trouble downloading the program. I have v2.79 of blender. 

I went to the blender addon page in settings and clicked on the zip file to import. Blender says it successful downloaded it. But it doesn't show up when I search it in addons. So basically I have it downloaded it but can't turn it on in the addons page.

**Comment by NumesSanguis** [comment]
You need an older release, not the current master, because that one is for Blender 2.80.
You can find v1.6.5b here (and read the notes): https://github.com/animate1978/MB-Lab/releases

**Comment by HoboJoeFish** [comment]
I downloaded that version and changed the name but it still would work. Blender would say it downloaded it, but it would not show up when I searched it in addons. I downloaded the clone of the current version onto my copy of blender 2.8 (which I have no idea how to use because it is so different) and it worked. So I think if I got a clone of the last version, then it would work. But I don’t know where I would find that.

**Comment by telnetr4** [comment]
Just to be clear: you scrolled down on the releases page and download MB 1.6.5 B, right?

**Comment by HoboJoeFish** [comment]
yes your are correct.

**Comment by animate1978** [comment]
I am going to be setting up a website where we all can download the versions. I have gotten many messages about having trouble downloading the addon from Github, plus this way the repository remains the development portion of MB-Lab while the site will have releases.

**Comment by animate1978** [comment]
This also brings to light the additional blend files we have added, this increased the file size by a lot, which probably is not helping in the downloading. So there is plans to have repositories for these as well so that the addon will not be so large in size again.

**Comment by HoboJoeFish** [comment]
okay, is there any way you can link me to a download now so I can use the addon?

**Comment by animate1978** [comment]
https://drive.google.com/file/d/1b_buiprCKRBXjqvYX-zAGZkziYXuwchn/view?usp=sharing

Try this link, I uploaded it onto my google drive.

**Comment by HoboJoeFish** [comment]
that worked. Thanks.

**Comment by telnetr4** [comment]
@animate1978 Are you using github.io for the website? I suggest using it.
