### ISSUE TITLE
UE4 shaders

### ISSUE THREAD

**Issue by philnguyen1994** [animate1978/MB-Lab#55]
I know MB-Lab is first and foremost designed for Blender Cycles but has anyone tried to use the latest MB-Lab 1.7.0 with Unreal Engine 4? If so, would you mind sharing your UE4 material? Or at least give some tips as to how to make the models look closest possible (I know it can never be 100%) to how they look in Blender Cycles?

**Comment by philnguyen1994** [comment]
Here's mine. It does a decent job for in-game character customization but the characters look pretty bad themselves (not even half as good as they look in Cycles)
![shader1](https://user-images.githubusercontent.com/46665867/51098550-a2fa7b00-17fd-11e9-9b8d-b912a89ab324.jpg)
![shader2](https://user-images.githubusercontent.com/46665867/51098549-a261e480-17fd-11e9-90e4-20789413aa58.jpg)

**Comment by animate1978** [comment]
I think it's a great idea.

**Comment by animate1978** [comment]
My UE4 Material is nowhere near as complex as yours, in fact I am taking pointers from your network.

**Comment by philnguyen1994** [comment]
It just looks complex because of all the in-game customizations trying to replicate the MB-Lab UI in Blender (skin color, muscle tone, etc). This is meant for RPGs etc with customizable player and NPCs. The actual 'shader' bit that makes the models look good is pretty weak honestly.

**Comment by Hopefullyidontgetbanned** [comment]
this looks quite nice, but skin details like veins and pores seem to be lost with this technique, as well the skin close ups seem very dry and not soft like most skin
