### ISSUE TITLE
rest pose not works for IK

### ISSUE THREAD

**Issue by millionart** [animate1978/MB-Lab#57]
**Describe the bug**
Characters created in IK mode cannot use rest post to change poses.

**To Reproduce**

1. Checked Use Inverse Kinematic
2. Create character
3. open Rest pose panel
4. select any pose or custom pose
5. just a little change

**Expected behavior**
I am not sure if this is a bug, intuitively it should work but in fact not.

**Comment by animate1978** [comment]
It is not a bug, Manuel coded it that way, not sure why, maybe technical reasoning?

**Comment by telnetr4** [comment]
If I remember correctly, all poses don't work for IK mode.

This is something that I believe should be investigated at some point. IMO, saying something isn't possible due to "technical reasoning" is usually shorthand for "I don't know how to do it effectively right now."

**Comment by animate1978** [comment]
LOL
