### ISSUE TITLE
Auto-modelling doesn't work on faces

### ISSUE THREAD

**Issue by telnetr4** [animate1978/MB-Lab#6]
After some testing, I'm fairly certain that auto-modeling doesn't work on faces.

This feature would be immensely useful and powerful for quickly making new characters.

**Comment by telnetr4** [comment]
Also, how do we change the labels on these?

**Comment by animate1978** [comment]
Yes I just tested that function, it alters the body but not the face. Not sure if we should be adding another random generator, as in the current random generator alters faces as well as the body so adding another one might be overkill. Not sure even where to begin with that anyway.

As for the labels, I think you are referring to the button labels? This for instance is changed, it was 'Init character' but have been changing the button labels to be more uniform.

`class StartSession(bpy.types.Operator):
    bl_idname = "mbast.init_character"
    bl_label = "Create character"
    bl_description = 'Create the character selected above'
    bl_context = 'objectmode'
    bl_options = {'REGISTER', 'INTERNAL','UNDO'}

    def execute(self, context):
        start_lab_session()
        return {'FINISHED'}`

**Comment by telnetr4** [comment]
> Not sure if we should be adding another random generator
Automodelling isnt a random generator. Its a drafting system. http://www.manuelbastioni.com/guide_automodelling_system.php

When I get a chance I'll try poking around in it.

By labels I mean the issue labels.

**Comment by animate1978** [comment]
I see what you mean now, I haven't poked too much into the docs yet, though I should.

As for the labels they are easy for me to change, add, edit etc... just let me know what you want to be a label because I am pretty sure only I can change them, I think because the repo is on my account.

**Comment by animate1978** [comment]
I just found this page as well where it reads "Automodelling system to face. First prototype of auto face modelling." - http://www.manuelbastioni.com/guide_features_planned_in_next_versions.php

**Comment by harmoniser** [comment]
Now, regarding face modelling in general, I have been trying to find a good workflow for this. As good as MB characters are, they will often need manual modelling of the face. So what I do is draft a character in MBL, then modify the face using character design drawings, 3D scans or sculpts. Sometimes it is enough to just shrinkwrap the MB mesh to a sculpt, but sometimes I just have to separate the head, split it and use the mirror modifier etc. (while preserving the original mesh topology/count, of course). Can be a bit of creative mess there until I really feel I have a well developed character.

However, when doing this with a MB character I lose the shape keys, weights for the armature and an unknown amount of all the magical features Manuel put there. I asked him how to best do what I need to do, and he just said I will lose all that.

Still I think that if MB Labs should be able to serve as a  effective tool for developing high-end characters, it should allow any level of artistic manual modifications. Not sure if there is a better workflow for this than I have found, or if this is something that can kept in mind in the ongoing development. If, for instance, there would be a way to make a "creative snapshot" of a character at any point, which is just a clean mesh that can be edited in any way as long as it retains the vertex structure, then merged back into the MB character which simply uses it as a blueprint for reshaping it's mesh. Or just import any mesh that has a certain identifiable structure (vertex count, topology, vertex groups) which then acts much like the list of numbers one can import now.

**Comment by animate1978** [comment]
The way that Manuel has coded MB-Lab and the associated JSON files, at this time until we can figure out HOW it all works any development towards new base meshes will have to wait.

Unfortunately we do not have the dev tools that Manuel has/had in order to create or edit the meshes of MB-Lab, we are still in the research phase there.
