### ISSUE TITLE
AutoModelling Bug

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#61]
**Describe the bug**
When clicking on the Auto Modelling button in the Auto Modelling Tools tab you get an error

```
The 'body_height_Z' measure not present in the analyzed database
Traceback (most recent call last):
  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\__in
it__.py", line 1632, in execute
    mblab_humanoid.automodelling(use_measures_from_current_obj=True)
  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\huma
noid.py", line 396, in automodelling
    similar_characters_data = self.morph_engine.compare_data_proportions()
  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\morp
hengine.py", line 263, in compare_data_proportions
    scores.append(self.compare_file_proportions(os.path.join(self.bodies_data_path, database_file)))

  File "C:\Users\farishta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab\morp
hengine.py", line 249, in compare_file_proportions
    v1 = mathutils.Vector(self.proportion_index)
TypeError: mathutils.Vector()

location: <unknown location>:-1

location: <unknown location>:-1

```

**To Reproduce**
1. Create a new character
2. Open Auto Modelling Tools tab
3. Click on Auto Modelling

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by animate1978** [comment]
Can't just revert back to original 1.7.0 version here, tried got syntax errors

**Comment by telnetr4** [comment]
Are you working directly off the master branch?

If so, you may want to consider making a second branch and working on the branch then merge the two whenever you finish something.

**Comment by animate1978** [comment]
I have a copy locally, off the master then copy these to the git repo.

I should make a development branch on GitHub.

**Comment by animate1978** [comment]
I almost have it working again, just have to change the logging

**Comment by animate1978** [comment]
Ok, logging is in place, not sure how optimized it is but the code produces no errors now.
