### ISSUE TITLE
Add the rendered image exception directly to the license

### ISSUE THREAD

**Issue by angavrilov** [animate1978/MB-Lab#75]
Considering that even things like fan art and fan fiction are considered derivative works of the original, I'm pretty sure that the reasoning about images rendered using models generated by the tool not being derivatives isn't legally sound. Thus it can only work as an explicit exception in the license.

Therefore, I suggest adding the text of paragraph 1.13 of https://github.com/animate1978/MB-Lab/wiki/Asset-Licensing directly to the license file distributed with the add-on, so that it won't be lost due to any kind of mistake.

**Comment by telnetr4** [comment]
That wiki page should just be a TLDR of the licenses already referenced in in the [license.txt](https://github.com/animate1978/MB-Lab/blob/master/license.txt) file. Whether or not we should include the simpler to understand version is debatable. I personally believe it's not necessary.

**Comment by animate1978** [comment]
It covers only the code, the data and the base models. GNU or AGPL depending on the license you are looking at.

It would be worth adding though I think, as mentioned above, so it does not get lost.

**Comment by animate1978** [comment]
It has been added to license as well as docs.
