### ISSUE TITLE
Cannot add this to Blender 2.8 on my mac

### ISSUE THREAD

**Issue by aaronspe** [animate1978/MB-Lab#80]
When I try to install this add-on I just get the spinning beach ball for a second and then the add-on window goes back to the default view. No feedback to why it isn't added.

**Comment by telnetr4** [comment]
Try installing the addon manually in the Finder. Extract the file into:
`/Users/{user}/Library/Application Support/Blender/2.80/`

**Comment by millionart** [comment]
#15

**Comment by aaronspe** [comment]
Thank you, that did it for me. File Utility expands the file ok, but unzipping from the terminal gives me a caution: filename not matched:  /User/user/Desktop message.

**Comment by aaronspe** [comment]
Thank you, manually expanding it worked. File Utility expands the file ok, but unzipping from the terminal gives me a caution: filename not matched:  /User/user/Desktop message.
