### ISSUE TITLE
Vertices files

### ISSUE THREAD

**Issue by telnetr4** [animate1978/MB-Lab#82]
Does anyone know how to generate the files in the vertices folder? I assume that it's just a list of all the vertices in the models.

**Comment by animate1978** [comment]
I've actually been trying to make sense of it, well all the json files actually.

**Comment by animate1978** [comment]
So I found out that JSON comes with Python, it has since 2.6 so there is natural import and export functionality there, I am not sure where to go from here but at least on the right path.

**Comment by telnetr4** [comment]
> I've actually been trying to make sense of it, well all the json files actually.

I've got a bit of an understanding of what each set does besides vertices.

Is there a tutorial that explains how to make a new character with your own geometry?

**Comment by animate1978** [comment]
Afraid not. The closest thing I managed to find was how to edit an armature on YouTube but nothing on how to make mesh from scratch.

I am afraid that we gotta figure it out alone.

**Comment by NumesSanguis** [comment]
I haven't looked into this add-on too much yet, but it seems the data in JSON files are 3D coordinates for points in space. Take for example `vertices/f_as01_verts.json`. It has 18210 data points. When we create with the add-on an Asian female and look at the vertices count (in Edit Mode)... we see Verts:18210.
@telnetr4 which means your first guess is right.

It could be that Manuel was using some other tool to create those files, which code is not included in the add-on itself. That could be as simple as a script in Blender that takes the current model in 3D view and exports the vertices to .json. However, it could also be that he uses an advanced script or external software. We'll have to look thoroughly through the code to find an indication of with what process they are made.
Maybe we could reverse the load process of the code that calls those .json files.

This is all speculation though, and I could be completely off.

Note: There is nothing special about .json, except that it's an easy format for most programming languages to parse. Those coordinates could have been saved in a .txt file or .xml.

**Comment by fnunnari** [comment]
I suggest sticking to JSON format. It is extremely easy to manage in Python.

If you need some code to read/write vertex groups, you can take inspiration from one of my project's utilities: <https://github.com/fnunnari/YALLAH/blob/master/BlenderScripts/addons/yallah/vertex_utils.py>

**Comment by animate1978** [comment]
https://discord.gg/FuJGcVN - is the Discord chat

As for the JSON files, I suspected that Manuel used a script to convert the data to JSON, we only need to find out how and write a script, hopefully, that will do that. Something like that is beyond my capabilities, however someone with some Python skills could probably do this. I have been combing through the code trying to find this, I think I have but again my coding skills are not good, I can read Python code I guess but coming up with new stuff is beyond me (yes I know I suck lol).

I will take a look at your code @fnunnari and see if some light comes from it

**Comment by telnetr4** [comment]
> As for the JSON files, I suspected that Manuel used a script to convert the data to JSON, we only need to find out how and write a script

This is why I'm asking: if this is the case, why isn't it just part of the addon code? If your addon can just generate it, why not just do that, store it in RAM and then use it while Blender is open without generating a file? Seems like a redundancy that bars a lot of people from making their own models.

It would make some more sense if this file acts as a cache, as I suspect making code that iterates through more than 18,000 vertices (after subdivision, which could be another explanation) would take a long time. Even then, if this is the case, its a poorly implemented cache as I cant seem to find a way for the addon to generate it, meaning the cache must be externally preset by the user, something that most trying to add their own geometries will find difficult.

**Comment by animate1978** [comment]
I am assuming that Manuel wanted to have more control over his addon, I guess that is why he made the JSON database as AGPL3, also stipulating that any modifications to the addon will void the CC0 license. So it seems that he did not want to make it so accessible to us, at least the models and the JSON files, not for modification that is.

I can understand why, modeling humans is not easy and there are hundreds of morphs, he was trying to protect the idea, the code, the models from being messed up. Maybe pride? I don't know.

I think this will be our biggest challenge.

**Comment by NumesSanguis** [comment]
I don't have time to verify this idea yet, but I think we can just create the template character, modify it a bit, and save all vertices back to a .json file. Maybe an approach like this add-on would work: https://github.com/nathanfaucett/Blender-JSON-Exporter

**Comment by animate1978** [comment]
https://github.com/animate1978/MB-Lab/wiki/Reverse-Engineering-JSON

This is a WIP wiki page but considering it relates to this

**Comment by animate1978** [comment]
Victory!

Using @Noizirom script, have been able to export vertice info to JSON!

**Comment by animate1978** [comment]
The script has been edited to have only 5 digits behind the decimal point, making the vertice JSON from us an exact replication of Manuel's JSON.

Before the values were WAY too precise ending up with JSON files that were more than double in size compared to the original.

**Comment by econundrum** [comment]
Are these files actually  ther vertices or are the vectors to be applied to the vertices of the base mesh from the blind to describe the model type.

E.g. did he take the base mesh, push and pull verts say for the African female phenotype then have a script that exported to json vectors that represented the difference between the base mesh and the phenotype mesh?

**Comment by Noizirom** [comment]
They are like you said a list of coordinates (vector3) from a model then
transferred to json. All the adjustments do is basically add or subtract to
the base verts to produce modifications by changing their locations.

**Comment by econundrum** [comment]
Yes, that makes sense I've been tracing it through the morphengine code just to improve my own  grasp of the the code and what it does with all these files.
