### ISSUE TITLE
Character Outfit creating process

### ISSUE THREAD

**Issue by DemonRem** [animate1978/MB-Lab#83]
Dear MB-Lab Team I wonder if it's possible to add a
option that will cut the full body to allow us to create faster cloth for example 
 once the character created there will be an option or something that will duplicate the model but only the body and half of leg 

![9b](https://user-images.githubusercontent.com/29927382/52584674-58d7da00-2e3b-11e9-8831-aa0dc1151c13.jpg)
![9a](https://user-images.githubusercontent.com/29927382/52584675-58d7da00-2e3b-11e9-8251-7f4eddef28e7.jpg)

**Comment by telnetr4** [comment]
Do you mean a way to hide the geometry under the clothing or a way to get the body geometry to make clothing?

If the latter, use the proxy feature.

**Comment by DemonRem** [comment]
body geometry to make clothing? yes

**Comment by telnetr4** [comment]
Sorry for the wait. https://github.com/animate1978/MB-Lab/wiki/Links#clothing is probably what you're looking for.

**Comment by telnetr4** [comment]
Did this help?

**Comment by DemonRem** [comment]
yes It does

**Comment by animate1978** [comment]
Awesome!!

I think we can close this now.
