### ISSUE TITLE
KeyError: 'eyes_albedo' at character finalization (prevents finalization)

### ISSUE THREAD

**Issue by NumesSanguis** [animate1978/MB-Lab#87]
**Describe the bug**
Texture for eye albedo missing? or is it undefined? Resulting in not being able to finalize character when "Save images and backup character" is selected.

**To Reproduce**
1. Create Caucasian female with "Use EEVEE materials ()" selected
2. Create character
3. Finalize Tools --> Finalize with textures and backup
    - Keep "Save images and backup character" selected
    - Give a Prefix name like "testy"
4. See error in console and character not finalized

**Expected behavior**
Not see an error when clicking finalize and having a finished finalized character.

**Screenshots**
![mb-lab_error_eye-albedo](https://user-images.githubusercontent.com/8008618/52895595-2db90600-3200-11e9-92cf-30fb9ae74515.png)

**Additional context**
If "Save images and backup character" is deselected, there is no error and it successfully finalizes.

**Logs**

    bpy.ops.object.delete(use_global=False, confirm=False)
    Traceback (most recent call last):
      File "C:\Users\*user*\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\__init__.py", line 1268, in execute
        mblab_humanoid.save_all_textures(self.filepath)
      File "C:\Users\*user*\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\humanoid.py", line 450, in save_all_textures
        self.mat_engine.save_texture(new_filepath,target)
      File "C:\Users\*user*\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-master\materialengine.py", line 244, in save_texture
        img_name = self.image_file_names[shader_target]
    KeyError: 'eyes_albedo'

    location: <unknown location>:-1

**Comment by animate1978** [comment]
This should not be happening, I am not sure what is different but I re-traced the steps but did not get an error.

Any way you can clone the repo again and test? I will do the same on my end

**Comment by animate1978** [comment]
This was caused by a typo, this has been fixed.
