### ISSUE TITLE
Improve teeth shader when using EEVEE

### ISSUE THREAD

**Issue by NumesSanguis** [animate1978/MB-Lab#88]
**Is your feature request related to a problem? Please describe.**
When rendering with EEVEE, the teeth look like graphics from the year 2000. Could this be upgraded to be more realistic?

**Describe the solution you'd like**
Improved EEVEE shaders for the teeth

**Describe alternatives you've considered**
Learn more about graphics and EEVEE so I know how I could do this myself :)

**Additional context**
![teeth](https://user-images.githubusercontent.com/8008618/52896055-db7ae380-3205-11e9-8361-7095f75925aa.png)

**Comment by animate1978** [comment]
Yikes, I have not spent a lot of time on the teeth. I will start working on it

**Comment by animate1978** [comment]
![screenshot from 2019-02-16 10-11-59](https://user-images.githubusercontent.com/479115/52902211-9938ae80-31d3-11e9-8487-bbb0073fff50.png)

Working on improvements to the teeth

**Comment by NumesSanguis** [comment]
Looking much better already :) Should the eyelashes also be made more transparent? Should I make a separate issue for that?

**Comment by animate1978** [comment]
No I am tackling all the shaders at once since I have the file open.

**Comment by animate1978** [comment]
EEVEE shaders have been improved, the teeth no longer look like Phong shading and the eyelash shader has correct blending mode applied.
