### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#89]
**Is your feature request related to a problem? Please describe.**

https://github.com/CGCookie/blender-addon-updater

So this popped up in my radar a few days ago, this can make updating code for users a lot easier considering this repository gets frequent updates per month.

**Describe the solution you'd like**
Get this added in at some point in time.

**Describe alternatives you've considered**
Not sure...

**Additional context**
...

**Comment by millionart** [comment]
I recommend only release a payment version on gumroad, users can choose to pay $0+ (free)  to download, and can get this automatic update function.
Millions of artists are looking for tools on gumroad, and some people are willing to sponsor a fee to thank developers. I think this is a benign cycle.

**Comment by animate1978** [comment]
I have put some thought into that however even if I put a payment version, for $0, on gumroad the code will still be available here.

The auto updater is simply just to allow users that are not wanting to clone each time we update, or users that aren't so adept with git.

**Comment by animate1978** [comment]
So I've added the initial code to the Dev branch, it is non functional. Not sure but I keep getting errors.

`rna_uiItemO: operator missing srna 'mb-lab.updater_check_now'
/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py:936
rna_uiItemO: operator missing srna 'mb-lab.updater_update_target'
/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py:1000
rna_uiItemO: operator missing srna 'mb-lab.updater_restore_backup'
/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py:1012
`

This happens when you go to the Preferences, then Addons, then expand the MB-Lab panel, this error above will repeat over and over for a bit. I am not sure what the issue is I think I followed directions pretty well and from other repos that also have this code added I've taken tips on.... does not make sense.

**Comment by animate1978** [comment]
Hmm and a side effect bug I just found, when unchecking MB-Lab in the Addons you will get this error 


Exception in module unregister(): '/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py'
Traceback (most recent call last):
  File "/home/farishta/blender_2_80_45/2.80/scripts/modules/addon_utils.py", line 446, in disable
    mod.unregister()
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 2372, in unregister
    addon_updater_ops.unregister()
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py", line 1416, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

Error: Traceback (most recent call last):
  File "/home/farishta/blender_2_80_45/2.80/scripts/modules/addon_utils.py", line 446, in disable
    mod.unregister()
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 2372, in unregister
    addon_updater_ops.unregister()
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/addon_updater_ops.py", line 1416, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

**Comment by animate1978** [comment]
THEN when you try to re check the addon to enable it again you will get THIS error AND MB_Lab stays disabled....


mb-lab updater verbose is enabled
Exception in module register(): /home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py
Traceback (most recent call last):
  File "/home/farishta/blender_2_80_45/2.80/scripts/modules/addon_utils.py", line 393, in enable
    mod.register()
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 2368, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass

**Comment by animate1978** [comment]
Seems there are now multiple issues related to the Auto-Updater code, regarding classes so this issue is re-opened

**Comment by noeinan** [comment]
I'm getting this same error with the package I downloaded today under v. 1.7.8 [here](https://mb-lab-community.github.io/MB-Lab.github.io/). Not able to enable the addon currently.
