### ISSUE TITLE
Add Animations...

### ISSUE THREAD

**Issue by BradWBeer** [animate1978/MB-Lab#9]
Much like poses, I would like to contribute default animations. Basics include walking, jogging, running, idle, strafe, backwards, etc. 

Because I am using Unreal Engine, I recommend 30 or 60 FPS and not 24. It makes the math difficult and the keyframes don't line up with the actual frames.

**Comment by WaraiOtoko** [comment]
I have no idea what the best choice for FPS is, but I don't think the choice should be based someones personal use-case.

**Comment by animate1978** [comment]
True however most game engines and modern video formats sync at 30 or 60 fps. 24 fps is commonly reserved for film itself and even then if released for NTSC it's frame rate is increased to 29.97, PAL is 25 fps. 2k and 4k is 24 fps, to keep in line with digital film standards. It's hard to really tell what this addon will be used for.

So animations might have to be labeled as GAME or FILM fps or something. So that maybe people can choose which fps animation for use case scenarios. Or something similar.

**Comment by NumesSanguis** [comment]
Would 120 fps make sense? It is both dividable by 24 and 30.

Also, with VR and such coming up, having a higher frame rate might be nice.
Furthermore, there is a great interest in this add-on (and MakeHuman) from researchers in the field of Human-Agent Interaction (HAI) and similar. In these types of research experiments, user often embody an avatar (in VR). Therefore, both smooth motion and body tracking is needed.
From Wikipedia: ["[full body spandex/lycra suit] can capture large numbers of markers at frame rates usually around 120 to 160 fps" and "[Time modulated active marker] motion capture systems are typically $20,000 for an eight camera, 12 megapixel spatial resolution 120 hertz system with one actor."](https://en.wikipedia.org/wiki/Motion_capture).
Furthermore, a quite common suit for motion tracking is the [Perception Neuron, which tracks at 120 fps with <18 sensors active](https://neuronmocap.com/forum/frames-second).

You would need 600 fps if you want it dividable by 24, 25 and 30.

**Comment by blaisefaint** [comment]
Here's a [video ](https://www.youtube.com/watch?v=VG9YfAxg9sA)showing what happened when I tried to animate the hands using the gestures that come with MB-Lab v1.70.

Please advise as how to avoid these problems in the future.

Thank you.

**Comment by animate1978** [comment]
Yikes. Honestly I have no idea.

**Comment by amirpavlo** [comment]
Regarding animation, have you guys used mixamo (now Adobe)? You can download a tone of animation from there. Would there be a problem with taking these animations and integrating them with MB-Lab?

**Comment by telnetr4** [comment]
> Regarding animation, have you guys used mixamo (now Adobe)? You can download a tone of animation from there. Would there be a problem with taking these animations and integrating them with MB-Lab?

I don't think so. As long as the license allows it (the FAQ says "You can use both characters and animations royalty free for personal, commercial, and non-profit projects") it should be fine.

TBH, it would be more useful to make going from MB-Lab to Mixamo easier until we develop more animation tools, seeing as the animations Mixamo can generate have more customization within Mixamo.

**Comment by amirpavlo** [comment]
Fair enough.

**Comment by animate1978** [comment]
Should be looked at as a "feature" for 1.7.5, a small library of animations in BVH format. We can animate, after Finalization, and then export this animation to BVH. I have tested this, at least in older versions of Blender and MB-Lab, and works perfect.

**Comment by animate1978** [comment]
Added a couple of animations, they are originally from Mixamo.... but they look a little rough, it's the basic idea I guess...

**Comment by mklemarczyk** [comment]
In my personal opinion the animations should be designed in the way that it is possible to apply any frame rate. I think if it would be possible to extract key poses from animation and let Blender compute transition instead of defining each frame as key frame.
In such way we can:
* adapt to any frame rate that suits you,
* modify dynamics of animation,
* alter and change poses in the animation (because there is no need to adjust all frames, only poses).

**Comment by blaisefaint** [comment]
My take on this is that we're in something of a wait-and-see-what-happens with Blender Animation 2020 situation, as the Blender Developers are planning to vastly re-work how animation works in Blender:
https://blenderartists.org/t/the-new-animation-system-2020-character-animation-system/1146794

**Comment by animate1978** [comment]
I haven't touched this for some time. I honestly think the animation engine is a bit rough altogether, however it is a nice feature.

I was about to say that BVH files don't store FPS info but they do

https://github.com/animate1978/MB-Lab/blob/b5885a0cbf9239084eb810239872d3d01b2bf1d2/data/animations/walking.bvh#L356

Interesting ideas

**Comment by Noizirom** [comment]
I could be mistaken, but can't you scale animations by scaling the
animation strips? I know at one point it was, but I haven't done any
animations in a long time.
